export interface CountryData {
  /** ISO 3166 Country/Region Name in English, e.g. Finland */
  name: string;
  /** Official State/Region Name in English, e.g. The Republic of Finland */
  officialName: string;
  /** Sovereignty Country/Region Code (Alpha-2), e.g. FI (for Åland Islands), UN (for Finland) */
  sovereignty: string;

  /** ISO 3166-1 Alpha-2 Country/Region Code, e.g. FI (for Finland) */
  code: string;
  /** ISO 3166-1 Alpha-3 Country/Region Code, e.g. FIN (for Finland) */
  alpha3Code: string;
  /** ISO 3166-1 Numeric Country/Region Code, e.g. 246 (for Finland) */
  numericCode: string;

  /** Internet Top-Level Domain (TLD) Name, e.g. .fi (for Finland) */
  topLevelDomain: string;

  /** ISO 4217 Currency Code, e.g. EUR (for Euro). Check @datalist/currency package for full data */
  currencyCode: string;
}

const countryDataList: CountryData[] = [
  {
    name: 'Afghanistan',
    officialName: 'The Islamic Republic of Afghanistan',
    sovereignty: 'UN member state',
    code: 'AF',
    alpha3Code: 'AFG',
    numericCode: '004',
    topLevelDomain: '.af',
    currencyCode: '',
  },
  {
    name: 'Åland Islands',
    officialName: 'Åland',
    sovereignty: 'Finland',
    code: 'AX',
    alpha3Code: 'ALA',
    numericCode: '248',
    topLevelDomain: '.ax',
    currencyCode: '',
  },
  {
    name: 'Albania',
    officialName: 'The Republic of Albania',
    sovereignty: 'UN member state',
    code: 'AL',
    alpha3Code: 'ALB',
    numericCode: '008',
    topLevelDomain: '.al',
    currencyCode: '',
  },
  {
    name: 'Algeria',
    officialName: "The People's Democratic Republic of Algeria",
    sovereignty: 'UN member state',
    code: 'DZ',
    alpha3Code: 'DZA',
    numericCode: '012',
    topLevelDomain: '.dz',
    currencyCode: '',
  },
  {
    name: 'American Samoa',
    officialName: 'The Territory of American Samoa',
    sovereignty: 'United States',
    code: 'AS',
    alpha3Code: 'ASM',
    numericCode: '016',
    topLevelDomain: '.as',
    currencyCode: '',
  },
  {
    name: 'Andorra',
    officialName: 'The Principality of Andorra',
    sovereignty: 'UN member state',
    code: 'AD',
    alpha3Code: 'AND',
    numericCode: '020',
    topLevelDomain: '.ad',
    currencyCode: '',
  },
  {
    name: 'Angola',
    officialName: 'The Republic of Angola',
    sovereignty: 'UN member state',
    code: 'AO',
    alpha3Code: 'AGO',
    numericCode: '024',
    topLevelDomain: '.ao',
    currencyCode: '',
  },
  {
    name: 'Anguilla',
    officialName: 'Anguilla',
    sovereignty: 'United Kingdom',
    code: 'AI',
    alpha3Code: 'AIA',
    numericCode: '660',
    topLevelDomain: '.ai',
    currencyCode: '',
  },
  {
    name: 'Antarctica',
    officialName: 'All land and ice shelves south of the 60th parallel south',
    sovereignty: 'Antarctic Treaty',
    code: 'AQ',
    alpha3Code: 'ATA',
    numericCode: '010',
    topLevelDomain: '.aq',
    currencyCode: '',
  },
  {
    name: 'Antigua and Barbuda',
    officialName: 'Antigua and Barbuda',
    sovereignty: 'UN member state',
    code: 'AG',
    alpha3Code: 'ATG',
    numericCode: '028',
    topLevelDomain: '.ag',
    currencyCode: '',
  },
  {
    name: 'Argentina',
    officialName: 'The Argentine Republic',
    sovereignty: 'UN member state',
    code: 'AR',
    alpha3Code: 'ARG',
    numericCode: '032',
    topLevelDomain: '.ar',
    currencyCode: '',
  },
  {
    name: 'Armenia',
    officialName: 'The Republic of Armenia',
    sovereignty: 'UN member state',
    code: 'AM',
    alpha3Code: 'ARM',
    numericCode: '051',
    topLevelDomain: '.am',
    currencyCode: '',
  },
  {
    name: 'Aruba',
    officialName: 'Aruba',
    sovereignty: 'Netherlands',
    code: 'AW',
    alpha3Code: 'ABW',
    numericCode: '533',
    topLevelDomain: '.aw',
    currencyCode: '',
  },
  {
    name: 'Australia',
    officialName: 'The Commonwealth of Australia',
    sovereignty: 'UN member state',
    code: 'AU',
    alpha3Code: 'AUS',
    numericCode: '036',
    topLevelDomain: '.au',
    currencyCode: '',
  },
  {
    name: 'Austria',
    officialName: 'The Republic of Austria',
    sovereignty: 'UN member state',
    code: 'AT',
    alpha3Code: 'AUT',
    numericCode: '040',
    topLevelDomain: '.at',
    currencyCode: '',
  },
  {
    name: 'Azerbaijan',
    officialName: 'The Republic of Azerbaijan',
    sovereignty: 'UN member state',
    code: 'AZ',
    alpha3Code: 'AZE',
    numericCode: '031',
    topLevelDomain: '.az',
    currencyCode: '',
  },
  {
    name: 'Bahamas',
    officialName: 'The Commonwealth of The Bahamas',
    sovereignty: 'UN member state',
    code: 'BS',
    alpha3Code: 'BHS',
    numericCode: '044',
    topLevelDomain: '.bs',
    currencyCode: '',
  },
  {
    name: 'Bahrain',
    officialName: 'The Kingdom of Bahrain',
    sovereignty: 'UN member state',
    code: 'BH',
    alpha3Code: 'BHR',
    numericCode: '048',
    topLevelDomain: '.bh',
    currencyCode: '',
  },
  {
    name: 'Bangladesh',
    officialName: "The People's Republic of Bangladesh",
    sovereignty: 'UN member state',
    code: 'BD',
    alpha3Code: 'BGD',
    numericCode: '050',
    topLevelDomain: '.bd',
    currencyCode: '',
  },
  {
    name: 'Barbados',
    officialName: 'Barbados',
    sovereignty: 'UN member state',
    code: 'BB',
    alpha3Code: 'BRB',
    numericCode: '052',
    topLevelDomain: '.bb',
    currencyCode: '',
  },
  {
    name: 'Belarus',
    officialName: 'The Republic of Belarus',
    sovereignty: 'UN member state',
    code: 'BY',
    alpha3Code: 'BLR',
    numericCode: '112',
    topLevelDomain: '.by',
    currencyCode: '',
  },
  {
    name: 'Belgium',
    officialName: 'The Kingdom of Belgium',
    sovereignty: 'UN member state',
    code: 'BE',
    alpha3Code: 'BEL',
    numericCode: '056',
    topLevelDomain: '.be',
    currencyCode: '',
  },
  {
    name: 'Belize',
    officialName: 'Belize',
    sovereignty: 'UN member state',
    code: 'BZ',
    alpha3Code: 'BLZ',
    numericCode: '084',
    topLevelDomain: '.bz',
    currencyCode: '',
  },
  {
    name: 'Benin',
    officialName: 'The Republic of Benin',
    sovereignty: 'UN member state',
    code: 'BJ',
    alpha3Code: 'BEN',
    numericCode: '204',
    topLevelDomain: '.bj',
    currencyCode: '',
  },
  {
    name: 'Bermuda',
    officialName: 'Bermuda',
    sovereignty: 'United Kingdom',
    code: 'BM',
    alpha3Code: 'BMU',
    numericCode: '060',
    topLevelDomain: '.bm',
    currencyCode: '',
  },
  {
    name: 'Bhutan',
    officialName: 'The Kingdom of Bhutan',
    sovereignty: 'UN member state',
    code: 'BT',
    alpha3Code: 'BTN',
    numericCode: '064',
    topLevelDomain: '.bt',
    currencyCode: '',
  },
  {
    name: 'Bolivia',
    officialName: 'The Plurinational State of Bolivia',
    sovereignty: 'UN member state',
    code: 'BO',
    alpha3Code: 'BOL',
    numericCode: '068',
    topLevelDomain: '.bo',
    currencyCode: '',
  },
  {
    name: 'Bonaire Sint Eustatius Saba',
    officialName: 'Bonaire, Sint Eustatius and Saba',
    sovereignty: 'Netherlands',
    code: 'BQ',
    alpha3Code: 'BES',
    numericCode: '535',
    topLevelDomain: '.bq .nl',
    currencyCode: '',
  },
  {
    name: 'Bosnia and Herzegovina',
    officialName: 'Bosnia and Herzegovina',
    sovereignty: 'UN member state',
    code: 'BA',
    alpha3Code: 'BIH',
    numericCode: '070',
    topLevelDomain: '.ba',
    currencyCode: '',
  },
  {
    name: 'Botswana',
    officialName: 'The Republic of Botswana',
    sovereignty: 'UN member state',
    code: 'BW',
    alpha3Code: 'BWA',
    numericCode: '072',
    topLevelDomain: '.bw',
    currencyCode: '',
  },
  {
    name: 'Bouvet Island',
    officialName: 'Bouvet Island',
    sovereignty: 'Norway',
    code: 'BV',
    alpha3Code: 'BVT',
    numericCode: '074',
    topLevelDomain: '',
    currencyCode: '',
  },
  {
    name: 'Brazil',
    officialName: 'The Federative Republic of Brazil',
    sovereignty: 'UN member state',
    code: 'BR',
    alpha3Code: 'BRA',
    numericCode: '076',
    topLevelDomain: '.br',
    currencyCode: '',
  },
  {
    name: 'British Indian Ocean Territory',
    officialName: 'The British Indian Ocean Territory',
    sovereignty: 'United Kingdom',
    code: 'IO',
    alpha3Code: 'IOT',
    numericCode: '086',
    topLevelDomain: '.io',
    currencyCode: '',
  },
  {
    name: 'Brunei Darussalam',
    officialName: 'The Nation of Brunei, the Abode of Peace',
    sovereignty: 'UN member state',
    code: 'BN',
    alpha3Code: 'BRN',
    numericCode: '096',
    topLevelDomain: '.bn',
    currencyCode: '',
  },
  {
    name: 'Bulgaria',
    officialName: 'The Republic of Bulgaria',
    sovereignty: 'UN member state',
    code: 'BG',
    alpha3Code: 'BGR',
    numericCode: '100',
    topLevelDomain: '.bg',
    currencyCode: '',
  },
  {
    name: 'Burkina Faso',
    officialName: 'Burkina Faso',
    sovereignty: 'UN member state',
    code: 'BF',
    alpha3Code: 'BFA',
    numericCode: '854',
    topLevelDomain: '.bf',
    currencyCode: '',
  },
  {
    name: 'Burundi',
    officialName: 'The Republic of Burundi',
    sovereignty: 'UN member state',
    code: 'BI',
    alpha3Code: 'BDI',
    numericCode: '108',
    topLevelDomain: '.bi',
    currencyCode: '',
  },
  {
    name: 'Cabo Verde',
    officialName: 'The Republic of Cabo Verde',
    sovereignty: 'UN member state',
    code: 'CV',
    alpha3Code: 'CPV',
    numericCode: '132',
    topLevelDomain: '.cv',
    currencyCode: '',
  },
  {
    name: 'Cambodia',
    officialName: 'The Kingdom of Cambodia',
    sovereignty: 'UN member state',
    code: 'KH',
    alpha3Code: 'KHM',
    numericCode: '116',
    topLevelDomain: '.kh',
    currencyCode: '',
  },
  {
    name: 'Cameroon',
    officialName: 'The Republic of Cameroon',
    sovereignty: 'UN member state',
    code: 'CM',
    alpha3Code: 'CMR',
    numericCode: '120',
    topLevelDomain: '.cm',
    currencyCode: '',
  },
  {
    name: 'Canada',
    officialName: 'Canada',
    sovereignty: 'UN member state',
    code: 'CA',
    alpha3Code: 'CAN',
    numericCode: '124',
    topLevelDomain: '.ca',
    currencyCode: '',
  },
  {
    name: 'Cayman Islands',
    officialName: 'The Cayman Islands',
    sovereignty: 'United Kingdom',
    code: 'KY',
    alpha3Code: 'CYM',
    numericCode: '136',
    topLevelDomain: '.ky',
    currencyCode: '',
  },
  {
    name: 'Central African Republic',
    officialName: 'The Central African Republic',
    sovereignty: 'UN member state',
    code: 'CF',
    alpha3Code: 'CAF',
    numericCode: '140',
    topLevelDomain: '.cf',
    currencyCode: '',
  },
  {
    name: 'Chad',
    officialName: 'The Republic of Chad',
    sovereignty: 'UN member state',
    code: 'TD',
    alpha3Code: 'TCD',
    numericCode: '148',
    topLevelDomain: '.td',
    currencyCode: '',
  },
  {
    name: 'Chile',
    officialName: 'The Republic of Chile',
    sovereignty: 'UN member state',
    code: 'CL',
    alpha3Code: 'CHL',
    numericCode: '152',
    topLevelDomain: '.cl',
    currencyCode: '',
  },
  {
    name: 'China',
    officialName: "The People's Republic of China",
    sovereignty: 'UN member state',
    code: 'CN',
    alpha3Code: 'CHN',
    numericCode: '156',
    topLevelDomain: '.cn',
    currencyCode: '',
  },
  {
    name: 'Christmas Island',
    officialName: 'The Territory of Christmas Island',
    sovereignty: 'Australia',
    code: 'CX',
    alpha3Code: 'CXR',
    numericCode: '162',
    topLevelDomain: '.cx',
    currencyCode: '',
  },
  {
    name: 'Cocos',
    officialName: 'The Territory of Cocos Islands',
    sovereignty: 'Australia',
    code: 'CC',
    alpha3Code: 'CCK',
    numericCode: '166',
    topLevelDomain: '.cc',
    currencyCode: '',
  },
  {
    name: 'Colombia',
    officialName: 'The Republic of Colombia',
    sovereignty: 'UN member state',
    code: 'CO',
    alpha3Code: 'COL',
    numericCode: '170',
    topLevelDomain: '.co',
    currencyCode: '',
  },
  {
    name: 'Comoros',
    officialName: 'The Union of the Comoros',
    sovereignty: 'UN member state',
    code: 'KM',
    alpha3Code: 'COM',
    numericCode: '174',
    topLevelDomain: '.km',
    currencyCode: '',
  },
  {
    name: 'Congo',
    officialName: 'The Democratic Republic of the Congo',
    sovereignty: 'UN member state',
    code: 'CD',
    alpha3Code: 'COD',
    numericCode: '180',
    topLevelDomain: '.cd',
    currencyCode: '',
  },
  {
    name: 'Congo',
    officialName: 'The Republic of the Congo',
    sovereignty: 'UN member state',
    code: 'CG',
    alpha3Code: 'COG',
    numericCode: '178',
    topLevelDomain: '.cg',
    currencyCode: '',
  },
  {
    name: 'Cook Islands',
    officialName: 'The Cook Islands',
    sovereignty: 'New Zealand',
    code: 'CK',
    alpha3Code: 'COK',
    numericCode: '184',
    topLevelDomain: '.ck',
    currencyCode: '',
  },
  {
    name: 'Costa Rica',
    officialName: 'The Republic of Costa Rica',
    sovereignty: 'UN member state',
    code: 'CR',
    alpha3Code: 'CRI',
    numericCode: '188',
    topLevelDomain: '.cr',
    currencyCode: '',
  },
  {
    name: "Côte d'Ivoire",
    officialName: "The Republic of Côte d'Ivoire",
    sovereignty: 'UN member state',
    code: 'CI',
    alpha3Code: 'CIV',
    numericCode: '384',
    topLevelDomain: '.ci',
    currencyCode: '',
  },
  {
    name: 'Croatia',
    officialName: 'The Republic of Croatia',
    sovereignty: 'UN member state',
    code: 'HR',
    alpha3Code: 'HRV',
    numericCode: '191',
    topLevelDomain: '.hr',
    currencyCode: '',
  },
  {
    name: 'Cuba',
    officialName: 'The Republic of Cuba',
    sovereignty: 'UN member state',
    code: 'CU',
    alpha3Code: 'CUB',
    numericCode: '192',
    topLevelDomain: '.cu',
    currencyCode: '',
  },
  {
    name: 'Curaçao',
    officialName: 'The Country of Curaçao',
    sovereignty: 'Netherlands',
    code: 'CW',
    alpha3Code: 'CUW',
    numericCode: '531',
    topLevelDomain: '.cw',
    currencyCode: '',
  },
  {
    name: 'Cyprus',
    officialName: 'The Republic of Cyprus',
    sovereignty: 'UN member state',
    code: 'CY',
    alpha3Code: 'CYP',
    numericCode: '196',
    topLevelDomain: '.cy',
    currencyCode: '',
  },
  {
    name: 'Czechia',
    officialName: 'The Czech Republic',
    sovereignty: 'UN member state',
    code: 'CZ',
    alpha3Code: 'CZE',
    numericCode: '203',
    topLevelDomain: '.cz',
    currencyCode: '',
  },
  {
    name: 'Denmark',
    officialName: 'The Kingdom of Denmark',
    sovereignty: 'UN member state',
    code: 'DK',
    alpha3Code: 'DNK',
    numericCode: '208',
    topLevelDomain: '.dk',
    currencyCode: '',
  },
  {
    name: 'Djibouti',
    officialName: 'The Republic of Djibouti',
    sovereignty: 'UN member state',
    code: 'DJ',
    alpha3Code: 'DJI',
    numericCode: '262',
    topLevelDomain: '.dj',
    currencyCode: '',
  },
  {
    name: 'Dominica',
    officialName: 'The Commonwealth of Dominica',
    sovereignty: 'UN member state',
    code: 'DM',
    alpha3Code: 'DMA',
    numericCode: '212',
    topLevelDomain: '.dm',
    currencyCode: '',
  },
  {
    name: 'Dominican Republic',
    officialName: 'The Dominican Republic',
    sovereignty: 'UN member state',
    code: 'DO',
    alpha3Code: 'DOM',
    numericCode: '214',
    topLevelDomain: '.do',
    currencyCode: '',
  },
  {
    name: 'Ecuador',
    officialName: 'The Republic of Ecuador',
    sovereignty: 'UN member state',
    code: 'EC',
    alpha3Code: 'ECU',
    numericCode: '218',
    topLevelDomain: '.ec',
    currencyCode: '',
  },
  {
    name: 'Egypt',
    officialName: 'The Arab Republic of Egypt',
    sovereignty: 'UN member state',
    code: 'EG',
    alpha3Code: 'EGY',
    numericCode: '818',
    topLevelDomain: '.eg',
    currencyCode: '',
  },
  {
    name: 'El Salvador',
    officialName: 'The Republic of El Salvador',
    sovereignty: 'UN member state',
    code: 'SV',
    alpha3Code: 'SLV',
    numericCode: '222',
    topLevelDomain: '.sv',
    currencyCode: '',
  },
  {
    name: 'Equatorial Guinea',
    officialName: 'The Republic of Equatorial Guinea',
    sovereignty: 'UN member state',
    code: 'GQ',
    alpha3Code: 'GNQ',
    numericCode: '226',
    topLevelDomain: '.gq',
    currencyCode: '',
  },
  {
    name: 'Eritrea',
    officialName: 'The State of Eritrea',
    sovereignty: 'UN member state',
    code: 'ER',
    alpha3Code: 'ERI',
    numericCode: '232',
    topLevelDomain: '.er',
    currencyCode: '',
  },
  {
    name: 'Estonia',
    officialName: 'The Republic of Estonia',
    sovereignty: 'UN member state',
    code: 'EE',
    alpha3Code: 'EST',
    numericCode: '233',
    topLevelDomain: '.ee',
    currencyCode: '',
  },
  {
    name: 'Eswatini',
    officialName: 'The Kingdom of Eswatini',
    sovereignty: 'UN member state',
    code: 'SZ',
    alpha3Code: 'SWZ',
    numericCode: '748',
    topLevelDomain: '.sz',
    currencyCode: '',
  },
  {
    name: 'Ethiopia',
    officialName: 'The Federal Democratic Republic of Ethiopia',
    sovereignty: 'UN member state',
    code: 'ET',
    alpha3Code: 'ETH',
    numericCode: '231',
    topLevelDomain: '.et',
    currencyCode: '',
  },
  {
    name: 'Falkland Islands',
    officialName: 'The Falkland Islands',
    sovereignty: 'United Kingdom',
    code: 'FK',
    alpha3Code: 'FLK',
    numericCode: '238',
    topLevelDomain: '.fk',
    currencyCode: '',
  },
  {
    name: 'Faroe Islands',
    officialName: 'The Faroe Islands',
    sovereignty: 'Denmark',
    code: 'FO',
    alpha3Code: 'FRO',
    numericCode: '234',
    topLevelDomain: '.fo',
    currencyCode: '',
  },
  {
    name: 'Fiji',
    officialName: 'The Republic of Fiji',
    sovereignty: 'UN member state',
    code: 'FJ',
    alpha3Code: 'FJI',
    numericCode: '242',
    topLevelDomain: '.fj',
    currencyCode: '',
  },
  {
    name: 'Finland',
    officialName: 'The Republic of Finland',
    sovereignty: 'UN member state',
    code: 'FI',
    alpha3Code: 'FIN',
    numericCode: '246',
    topLevelDomain: '.fi',
    currencyCode: '',
  },
  {
    name: 'France',
    officialName: 'The French Republic',
    sovereignty: 'UN member state',
    code: 'FR',
    alpha3Code: 'FRA',
    numericCode: '250',
    topLevelDomain: '.fr',
    currencyCode: '',
  },
  {
    name: 'French Guiana',
    officialName: 'Guyane',
    sovereignty: 'France',
    code: 'GF',
    alpha3Code: 'GUF',
    numericCode: '254',
    topLevelDomain: '.gf',
    currencyCode: '',
  },
  {
    name: 'French Polynesia',
    officialName: 'French Polynesia',
    sovereignty: 'France',
    code: 'PF',
    alpha3Code: 'PYF',
    numericCode: '258',
    topLevelDomain: '.pf',
    currencyCode: '',
  },
  {
    name: 'French Southern Territories',
    officialName: 'The French Southern and Antarctic Lands',
    sovereignty: 'France',
    code: 'TF',
    alpha3Code: 'ATF',
    numericCode: '260',
    topLevelDomain: '.tf',
    currencyCode: '',
  },
  {
    name: 'Gabon',
    officialName: 'The Gabonese Republic',
    sovereignty: 'UN member state',
    code: 'GA',
    alpha3Code: 'GAB',
    numericCode: '266',
    topLevelDomain: '.ga',
    currencyCode: '',
  },
  {
    name: 'Gambia',
    officialName: 'The Republic of The Gambia',
    sovereignty: 'UN member state',
    code: 'GM',
    alpha3Code: 'GMB',
    numericCode: '270',
    topLevelDomain: '.gm',
    currencyCode: '',
  },
  {
    name: 'Georgia',
    officialName: 'Georgia',
    sovereignty: 'UN member state',
    code: 'GE',
    alpha3Code: 'GEO',
    numericCode: '268',
    topLevelDomain: '.ge',
    currencyCode: '',
  },
  {
    name: 'Germany',
    officialName: 'The Federal Republic of Germany',
    sovereignty: 'UN member state',
    code: 'DE',
    alpha3Code: 'DEU',
    numericCode: '276',
    topLevelDomain: '.de',
    currencyCode: '',
  },
  {
    name: 'Ghana',
    officialName: 'The Republic of Ghana',
    sovereignty: 'UN member state',
    code: 'GH',
    alpha3Code: 'GHA',
    numericCode: '288',
    topLevelDomain: '.gh',
    currencyCode: '',
  },
  {
    name: 'Gibraltar',
    officialName: 'Gibraltar',
    sovereignty: 'United Kingdom',
    code: 'GI',
    alpha3Code: 'GIB',
    numericCode: '292',
    topLevelDomain: '.gi',
    currencyCode: '',
  },
  {
    name: 'Greece',
    officialName: 'The Hellenic Republic',
    sovereignty: 'UN member state',
    code: 'GR',
    alpha3Code: 'GRC',
    numericCode: '300',
    topLevelDomain: '.gr',
    currencyCode: '',
  },
  {
    name: 'Greenland',
    officialName: 'Kalaallit Nunaat',
    sovereignty: 'Denmark',
    code: 'GL',
    alpha3Code: 'GRL',
    numericCode: '304',
    topLevelDomain: '.gl',
    currencyCode: '',
  },
  {
    name: 'Grenada',
    officialName: 'Grenada',
    sovereignty: 'UN member state',
    code: 'GD',
    alpha3Code: 'GRD',
    numericCode: '308',
    topLevelDomain: '.gd',
    currencyCode: '',
  },
  {
    name: 'Guadeloupe',
    officialName: 'Guadeloupe',
    sovereignty: 'France',
    code: 'GP',
    alpha3Code: 'GLP',
    numericCode: '312',
    topLevelDomain: '.gp',
    currencyCode: '',
  },
  {
    name: 'Guam',
    officialName: 'The Territory of Guam',
    sovereignty: 'United States',
    code: 'GU',
    alpha3Code: 'GUM',
    numericCode: '316',
    topLevelDomain: '.gu',
    currencyCode: '',
  },
  {
    name: 'Guatemala',
    officialName: 'The Republic of Guatemala',
    sovereignty: 'UN member state',
    code: 'GT',
    alpha3Code: 'GTM',
    numericCode: '320',
    topLevelDomain: '.gt',
    currencyCode: '',
  },
  {
    name: 'Guernsey',
    officialName: 'The Bailiwick of Guernsey',
    sovereignty: 'British Crown',
    code: 'GG',
    alpha3Code: 'GGY',
    numericCode: '831',
    topLevelDomain: '.gg',
    currencyCode: '',
  },
  {
    name: 'Guinea',
    officialName: 'The Republic of Guinea',
    sovereignty: 'UN member state',
    code: 'GN',
    alpha3Code: 'GIN',
    numericCode: '324',
    topLevelDomain: '.gn',
    currencyCode: '',
  },
  {
    name: 'Guinea-Bissau',
    officialName: 'The Republic of Guinea-Bissau',
    sovereignty: 'UN member state',
    code: 'GW',
    alpha3Code: 'GNB',
    numericCode: '624',
    topLevelDomain: '.gw',
    currencyCode: '',
  },
  {
    name: 'Guyana',
    officialName: 'The Co-operative Republic of Guyana',
    sovereignty: 'UN member state',
    code: 'GY',
    alpha3Code: 'GUY',
    numericCode: '328',
    topLevelDomain: '.gy',
    currencyCode: '',
  },
  {
    name: 'Haiti',
    officialName: 'The Republic of Haiti',
    sovereignty: 'UN member state',
    code: 'HT',
    alpha3Code: 'HTI',
    numericCode: '332',
    topLevelDomain: '.ht',
    currencyCode: '',
  },
  {
    name: 'Heard Island and McDonald Islands',
    officialName: 'The Territory of Heard Island and McDonald Islands',
    sovereignty: 'Australia',
    code: 'HM',
    alpha3Code: 'HMD',
    numericCode: '334',
    topLevelDomain: '.hm',
    currencyCode: '',
  },
  {
    name: 'Holy See',
    officialName: 'The Holy See',
    sovereignty: 'UN observer state',
    code: 'VA',
    alpha3Code: 'VAT',
    numericCode: '336',
    topLevelDomain: '.va',
    currencyCode: '',
  },
  {
    name: 'Honduras',
    officialName: 'The Republic of Honduras',
    sovereignty: 'UN member state',
    code: 'HN',
    alpha3Code: 'HND',
    numericCode: '340',
    topLevelDomain: '.hn',
    currencyCode: '',
  },
  {
    name: 'Hong Kong',
    officialName: 'The Hong Kong Special Administrative Region of China',
    sovereignty: 'China',
    code: 'HK',
    alpha3Code: 'HKG',
    numericCode: '344',
    topLevelDomain: '.hk',
    currencyCode: '',
  },
  {
    name: 'Hungary',
    officialName: 'Hungary',
    sovereignty: 'UN member state',
    code: 'HU',
    alpha3Code: 'HUN',
    numericCode: '348',
    topLevelDomain: '.hu',
    currencyCode: '',
  },
  {
    name: 'Iceland',
    officialName: 'Iceland',
    sovereignty: 'UN member state',
    code: 'IS',
    alpha3Code: 'ISL',
    numericCode: '352',
    topLevelDomain: '.is',
    currencyCode: '',
  },
  {
    name: 'India',
    officialName: 'The Republic of India',
    sovereignty: 'UN member state',
    code: 'IN',
    alpha3Code: 'IND',
    numericCode: '356',
    topLevelDomain: '.in',
    currencyCode: '',
  },
  {
    name: 'Indonesia',
    officialName: 'The Republic of Indonesia',
    sovereignty: 'UN member state',
    code: 'ID',
    alpha3Code: 'IDN',
    numericCode: '360',
    topLevelDomain: '.id',
    currencyCode: '',
  },
  {
    name: 'Iran',
    officialName: 'The Islamic Republic of Iran',
    sovereignty: 'UN member state',
    code: 'IR',
    alpha3Code: 'IRN',
    numericCode: '364',
    topLevelDomain: '.ir',
    currencyCode: '',
  },
  {
    name: 'Iraq',
    officialName: 'The Republic of Iraq',
    sovereignty: 'UN member state',
    code: 'IQ',
    alpha3Code: 'IRQ',
    numericCode: '368',
    topLevelDomain: '.iq',
    currencyCode: '',
  },
  {
    name: 'Ireland',
    officialName: 'Ireland',
    sovereignty: 'UN member state',
    code: 'IE',
    alpha3Code: 'IRL',
    numericCode: '372',
    topLevelDomain: '.ie',
    currencyCode: '',
  },
  {
    name: 'Isle of Man',
    officialName: 'The Isle of Man',
    sovereignty: 'British Crown',
    code: 'IM',
    alpha3Code: 'IMN',
    numericCode: '833',
    topLevelDomain: '.im',
    currencyCode: '',
  },
  {
    name: 'Israel',
    officialName: 'The State of Israel',
    sovereignty: 'UN member state',
    code: 'IL',
    alpha3Code: 'ISR',
    numericCode: '376',
    topLevelDomain: '.il',
    currencyCode: '',
  },
  {
    name: 'Italy',
    officialName: 'The Italian Republic',
    sovereignty: 'UN member state',
    code: 'IT',
    alpha3Code: 'ITA',
    numericCode: '380',
    topLevelDomain: '.it',
    currencyCode: '',
  },
  {
    name: 'Jamaica',
    officialName: 'Jamaica',
    sovereignty: 'UN member state',
    code: 'JM',
    alpha3Code: 'JAM',
    numericCode: '388',
    topLevelDomain: '.jm',
    currencyCode: '',
  },
  {
    name: 'Japan',
    officialName: 'Japan',
    sovereignty: 'UN member state',
    code: 'JP',
    alpha3Code: 'JPN',
    numericCode: '392',
    topLevelDomain: '.jp',
    currencyCode: '',
  },
  {
    name: 'Jersey',
    officialName: 'The Bailiwick of Jersey',
    sovereignty: 'British Crown',
    code: 'JE',
    alpha3Code: 'JEY',
    numericCode: '832',
    topLevelDomain: '.je',
    currencyCode: '',
  },
  {
    name: 'Jordan',
    officialName: 'The Hashemite Kingdom of Jordan',
    sovereignty: 'UN member state',
    code: 'JO',
    alpha3Code: 'JOR',
    numericCode: '400',
    topLevelDomain: '.jo',
    currencyCode: '',
  },
  {
    name: 'Kazakhstan',
    officialName: 'The Republic of Kazakhstan',
    sovereignty: 'UN member state',
    code: 'KZ',
    alpha3Code: 'KAZ',
    numericCode: '398',
    topLevelDomain: '.kz',
    currencyCode: '',
  },
  {
    name: 'Kenya',
    officialName: 'The Republic of Kenya',
    sovereignty: 'UN member state',
    code: 'KE',
    alpha3Code: 'KEN',
    numericCode: '404',
    topLevelDomain: '.ke',
    currencyCode: '',
  },
  {
    name: 'Kiribati',
    officialName: 'The Republic of Kiribati',
    sovereignty: 'UN member state',
    code: 'KI',
    alpha3Code: 'KIR',
    numericCode: '296',
    topLevelDomain: '.ki',
    currencyCode: '',
  },
  {
    name: 'Korea',
    officialName: "The Democratic People's Republic of Korea",
    sovereignty: 'UN member state',
    code: 'KP',
    alpha3Code: 'PRK',
    numericCode: '408',
    topLevelDomain: '.kp',
    currencyCode: '',
  },
  {
    name: 'Korea',
    officialName: 'The Republic of Korea',
    sovereignty: 'UN member state',
    code: 'KR',
    alpha3Code: 'KOR',
    numericCode: '410',
    topLevelDomain: '.kr',
    currencyCode: '',
  },
  {
    name: 'Kuwait',
    officialName: 'The State of Kuwait',
    sovereignty: 'UN member state',
    code: 'KW',
    alpha3Code: 'KWT',
    numericCode: '414',
    topLevelDomain: '.kw',
    currencyCode: '',
  },
  {
    name: 'Kyrgyzstan',
    officialName: 'The Kyrgyz Republic',
    sovereignty: 'UN member state',
    code: 'KG',
    alpha3Code: 'KGZ',
    numericCode: '417',
    topLevelDomain: '.kg',
    currencyCode: '',
  },
  {
    name: "Lao People's Democratic Republic",
    officialName: "The Lao People's Democratic Republic",
    sovereignty: 'UN member state',
    code: 'LA',
    alpha3Code: 'LAO',
    numericCode: '418',
    topLevelDomain: '.la',
    currencyCode: '',
  },
  {
    name: 'Latvia',
    officialName: 'The Republic of Latvia',
    sovereignty: 'UN member state',
    code: 'LV',
    alpha3Code: 'LVA',
    numericCode: '428',
    topLevelDomain: '.lv',
    currencyCode: '',
  },
  {
    name: 'Lebanon',
    officialName: 'The Lebanese Republic',
    sovereignty: 'UN member state',
    code: 'LB',
    alpha3Code: 'LBN',
    numericCode: '422',
    topLevelDomain: '.lb',
    currencyCode: '',
  },
  {
    name: 'Lesotho',
    officialName: 'The Kingdom of Lesotho',
    sovereignty: 'UN member state',
    code: 'LS',
    alpha3Code: 'LSO',
    numericCode: '426',
    topLevelDomain: '.ls',
    currencyCode: '',
  },
  {
    name: 'Liberia',
    officialName: 'The Republic of Liberia',
    sovereignty: 'UN member state',
    code: 'LR',
    alpha3Code: 'LBR',
    numericCode: '430',
    topLevelDomain: '.lr',
    currencyCode: '',
  },
  {
    name: 'Libya',
    officialName: 'The State of Libya',
    sovereignty: 'UN member state',
    code: 'LY',
    alpha3Code: 'LBY',
    numericCode: '434',
    topLevelDomain: '.ly',
    currencyCode: '',
  },
  {
    name: 'Liechtenstein',
    officialName: 'The Principality of Liechtenstein',
    sovereignty: 'UN member state',
    code: 'LI',
    alpha3Code: 'LIE',
    numericCode: '438',
    topLevelDomain: '.li',
    currencyCode: '',
  },
  {
    name: 'Lithuania',
    officialName: 'The Republic of Lithuania',
    sovereignty: 'UN member state',
    code: 'LT',
    alpha3Code: 'LTU',
    numericCode: '440',
    topLevelDomain: '.lt',
    currencyCode: '',
  },
  {
    name: 'Luxembourg',
    officialName: 'The Grand Duchy of Luxembourg',
    sovereignty: 'UN member state',
    code: 'LU',
    alpha3Code: 'LUX',
    numericCode: '442',
    topLevelDomain: '.lu',
    currencyCode: '',
  },
  {
    name: 'Macao',
    officialName: 'The Macao Special Administrative Region of China',
    sovereignty: 'China',
    code: 'MO',
    alpha3Code: 'MAC',
    numericCode: '446',
    topLevelDomain: '.mo',
    currencyCode: '',
  },
  {
    name: 'North Macedonia',
    officialName: 'The Republic of North Macedonia',
    sovereignty: 'UN member state',
    code: 'MK',
    alpha3Code: 'MKD',
    numericCode: '807',
    topLevelDomain: '.mk',
    currencyCode: '',
  },
  {
    name: 'Madagascar',
    officialName: 'The Republic of Madagascar',
    sovereignty: 'UN member state',
    code: 'MG',
    alpha3Code: 'MDG',
    numericCode: '450',
    topLevelDomain: '.mg',
    currencyCode: '',
  },
  {
    name: 'Malawi',
    officialName: 'The Republic of Malawi',
    sovereignty: 'UN member state',
    code: 'MW',
    alpha3Code: 'MWI',
    numericCode: '454',
    topLevelDomain: '.mw',
    currencyCode: '',
  },
  {
    name: 'Malaysia',
    officialName: 'Malaysia',
    sovereignty: 'UN member state',
    code: 'MY',
    alpha3Code: 'MYS',
    numericCode: '458',
    topLevelDomain: '.my',
    currencyCode: '',
  },
  {
    name: 'Maldives',
    officialName: 'The Republic of Maldives',
    sovereignty: 'UN member state',
    code: 'MV',
    alpha3Code: 'MDV',
    numericCode: '462',
    topLevelDomain: '.mv',
    currencyCode: '',
  },
  {
    name: 'Mali',
    officialName: 'The Republic of Mali',
    sovereignty: 'UN member state',
    code: 'ML',
    alpha3Code: 'MLI',
    numericCode: '466',
    topLevelDomain: '.ml',
    currencyCode: '',
  },
  {
    name: 'Malta',
    officialName: 'The Republic of Malta',
    sovereignty: 'UN member state',
    code: 'MT',
    alpha3Code: 'MLT',
    numericCode: '470',
    topLevelDomain: '.mt',
    currencyCode: '',
  },
  {
    name: 'Marshall Islands',
    officialName: 'The Republic of the Marshall Islands',
    sovereignty: 'UN member state',
    code: 'MH',
    alpha3Code: 'MHL',
    numericCode: '584',
    topLevelDomain: '.mh',
    currencyCode: '',
  },
  {
    name: 'Martinique',
    officialName: 'Martinique',
    sovereignty: 'France',
    code: 'MQ',
    alpha3Code: 'MTQ',
    numericCode: '474',
    topLevelDomain: '.mq',
    currencyCode: '',
  },
  {
    name: 'Mauritania',
    officialName: 'The Islamic Republic of Mauritania',
    sovereignty: 'UN member state',
    code: 'MR',
    alpha3Code: 'MRT',
    numericCode: '478',
    topLevelDomain: '.mr',
    currencyCode: '',
  },
  {
    name: 'Mauritius',
    officialName: 'The Republic of Mauritius',
    sovereignty: 'UN member state',
    code: 'MU',
    alpha3Code: 'MUS',
    numericCode: '480',
    topLevelDomain: '.mu',
    currencyCode: '',
  },
  {
    name: 'Mayotte',
    officialName: 'The Department of Mayotte',
    sovereignty: 'France',
    code: 'YT',
    alpha3Code: 'MYT',
    numericCode: '175',
    topLevelDomain: '.yt',
    currencyCode: '',
  },
  {
    name: 'Mexico',
    officialName: 'The United Mexican States',
    sovereignty: 'UN member state',
    code: 'MX',
    alpha3Code: 'MEX',
    numericCode: '484',
    topLevelDomain: '.mx',
    currencyCode: '',
  },
  {
    name: 'Micronesia',
    officialName: 'The Federated States of Micronesia',
    sovereignty: 'UN member state',
    code: 'FM',
    alpha3Code: 'FSM',
    numericCode: '583',
    topLevelDomain: '.fm',
    currencyCode: '',
  },
  {
    name: 'Moldova',
    officialName: 'The Republic of Moldova',
    sovereignty: 'UN member state',
    code: 'MD',
    alpha3Code: 'MDA',
    numericCode: '498',
    topLevelDomain: '.md',
    currencyCode: '',
  },
  {
    name: 'Monaco',
    officialName: 'The Principality of Monaco',
    sovereignty: 'UN member state',
    code: 'MC',
    alpha3Code: 'MCO',
    numericCode: '492',
    topLevelDomain: '.mc',
    currencyCode: '',
  },
  {
    name: 'Mongolia',
    officialName: 'Mongolia',
    sovereignty: 'UN member state',
    code: 'MN',
    alpha3Code: 'MNG',
    numericCode: '496',
    topLevelDomain: '.mn',
    currencyCode: '',
  },
  {
    name: 'Montenegro',
    officialName: 'Montenegro',
    sovereignty: 'UN member state',
    code: 'ME',
    alpha3Code: 'MNE',
    numericCode: '499',
    topLevelDomain: '.me',
    currencyCode: '',
  },
  {
    name: 'Montserrat',
    officialName: 'Montserrat',
    sovereignty: 'United Kingdom',
    code: 'MS',
    alpha3Code: 'MSR',
    numericCode: '500',
    topLevelDomain: '.ms',
    currencyCode: '',
  },
  {
    name: 'Morocco',
    officialName: 'The Kingdom of Morocco',
    sovereignty: 'UN member state',
    code: 'MA',
    alpha3Code: 'MAR',
    numericCode: '504',
    topLevelDomain: '.ma',
    currencyCode: '',
  },
  {
    name: 'Mozambique',
    officialName: 'The Republic of Mozambique',
    sovereignty: 'UN member state',
    code: 'MZ',
    alpha3Code: 'MOZ',
    numericCode: '508',
    topLevelDomain: '.mz',
    currencyCode: '',
  },
  {
    name: 'Myanmar',
    officialName: 'The Republic of the Union of Myanmar',
    sovereignty: 'UN member state',
    code: 'MM',
    alpha3Code: 'MMR',
    numericCode: '104',
    topLevelDomain: '.mm',
    currencyCode: '',
  },
  {
    name: 'Namibia',
    officialName: 'The Republic of Namibia',
    sovereignty: 'UN member state',
    code: 'NA',
    alpha3Code: 'NAM',
    numericCode: '516',
    topLevelDomain: '.na',
    currencyCode: '',
  },
  {
    name: 'Nauru',
    officialName: 'The Republic of Nauru',
    sovereignty: 'UN member state',
    code: 'NR',
    alpha3Code: 'NRU',
    numericCode: '520',
    topLevelDomain: '.nr',
    currencyCode: '',
  },
  {
    name: 'Nepal',
    officialName: 'The Federal Democratic Republic of Nepal',
    sovereignty: 'UN member state',
    code: 'NP',
    alpha3Code: 'NPL',
    numericCode: '524',
    topLevelDomain: '.np',
    currencyCode: '',
  },
  {
    name: 'Netherlands',
    officialName: 'The Kingdom of the Netherlands',
    sovereignty: 'UN member state',
    code: 'NL',
    alpha3Code: 'NLD',
    numericCode: '528',
    topLevelDomain: '.nl',
    currencyCode: '',
  },
  {
    name: 'New Caledonia',
    officialName: 'New Caledonia',
    sovereignty: 'France',
    code: 'NC',
    alpha3Code: 'NCL',
    numericCode: '540',
    topLevelDomain: '.nc',
    currencyCode: '',
  },
  {
    name: 'New Zealand',
    officialName: 'New Zealand',
    sovereignty: 'UN member state',
    code: 'NZ',
    alpha3Code: 'NZL',
    numericCode: '554',
    topLevelDomain: '.nz',
    currencyCode: '',
  },
  {
    name: 'Nicaragua',
    officialName: 'The Republic of Nicaragua',
    sovereignty: 'UN member state',
    code: 'NI',
    alpha3Code: 'NIC',
    numericCode: '558',
    topLevelDomain: '.ni',
    currencyCode: '',
  },
  {
    name: 'Niger',
    officialName: 'The Republic of the Niger',
    sovereignty: 'UN member state',
    code: 'NE',
    alpha3Code: 'NER',
    numericCode: '562',
    topLevelDomain: '.ne',
    currencyCode: '',
  },
  {
    name: 'Nigeria',
    officialName: 'The Federal Republic of Nigeria',
    sovereignty: 'UN member state',
    code: 'NG',
    alpha3Code: 'NGA',
    numericCode: '566',
    topLevelDomain: '.ng',
    currencyCode: '',
  },
  {
    name: 'Niue',
    officialName: 'Niue',
    sovereignty: 'New Zealand',
    code: 'NU',
    alpha3Code: 'NIU',
    numericCode: '570',
    topLevelDomain: '.nu',
    currencyCode: '',
  },
  {
    name: 'Norfolk Island',
    officialName: 'The Territory of Norfolk Island',
    sovereignty: 'Australia',
    code: 'NF',
    alpha3Code: 'NFK',
    numericCode: '574',
    topLevelDomain: '.nf',
    currencyCode: '',
  },
  {
    name: 'Northern Mariana Islands',
    officialName: 'The Commonwealth of the Northern Mariana Islands',
    sovereignty: 'United States',
    code: 'MP',
    alpha3Code: 'MNP',
    numericCode: '580',
    topLevelDomain: '.mp',
    currencyCode: '',
  },
  {
    name: 'Norway',
    officialName: 'The Kingdom of Norway',
    sovereignty: 'UN member state',
    code: 'NO',
    alpha3Code: 'NOR',
    numericCode: '578',
    topLevelDomain: '.no',
    currencyCode: '',
  },
  {
    name: 'Oman',
    officialName: 'The Sultanate of Oman',
    sovereignty: 'UN member state',
    code: 'OM',
    alpha3Code: 'OMN',
    numericCode: '512',
    topLevelDomain: '.om',
    currencyCode: '',
  },
  {
    name: 'Pakistan',
    officialName: 'The Islamic Republic of Pakistan',
    sovereignty: 'UN member state',
    code: 'PK',
    alpha3Code: 'PAK',
    numericCode: '586',
    topLevelDomain: '.pk',
    currencyCode: '',
  },
  {
    name: 'Palau',
    officialName: 'The Republic of Palau',
    sovereignty: 'UN member state',
    code: 'PW',
    alpha3Code: 'PLW',
    numericCode: '585',
    topLevelDomain: '.pw',
    currencyCode: '',
  },
  {
    name: 'Palestine, State of',
    officialName: 'The State of Palestine',
    sovereignty: 'UN observer state',
    code: 'PS',
    alpha3Code: 'PSE',
    numericCode: '275',
    topLevelDomain: '.ps',
    currencyCode: '',
  },
  {
    name: 'Panama',
    officialName: 'The Republic of Panamá',
    sovereignty: 'UN member state',
    code: 'PA',
    alpha3Code: 'PAN',
    numericCode: '591',
    topLevelDomain: '.pa',
    currencyCode: '',
  },
  {
    name: 'Papua New Guinea',
    officialName: 'The Independent State of Papua New Guinea',
    sovereignty: 'UN member state',
    code: 'PG',
    alpha3Code: 'PNG',
    numericCode: '598',
    topLevelDomain: '.pg',
    currencyCode: '',
  },
  {
    name: 'Paraguay',
    officialName: 'The Republic of Paraguay',
    sovereignty: 'UN member state',
    code: 'PY',
    alpha3Code: 'PRY',
    numericCode: '600',
    topLevelDomain: '.py',
    currencyCode: '',
  },
  {
    name: 'Peru',
    officialName: 'The Republic of Perú',
    sovereignty: 'UN member state',
    code: 'PE',
    alpha3Code: 'PER',
    numericCode: '604',
    topLevelDomain: '.pe',
    currencyCode: '',
  },
  {
    name: 'Philippines',
    officialName: 'The Republic of the Philippines',
    sovereignty: 'UN member state',
    code: 'PH',
    alpha3Code: 'PHL',
    numericCode: '608',
    topLevelDomain: '.ph',
    currencyCode: '',
  },
  {
    name: 'Pitcairn',
    officialName: 'The Pitcairn, Henderson, Ducie and Oeno Islands',
    sovereignty: 'United Kingdom',
    code: 'PN',
    alpha3Code: 'PCN',
    numericCode: '612',
    topLevelDomain: '.pn',
    currencyCode: '',
  },
  {
    name: 'Poland',
    officialName: 'The Republic of Poland',
    sovereignty: 'UN member state',
    code: 'PL',
    alpha3Code: 'POL',
    numericCode: '616',
    topLevelDomain: '.pl',
    currencyCode: '',
  },
  {
    name: 'Portugal',
    officialName: 'The Portuguese Republic',
    sovereignty: 'UN member state',
    code: 'PT',
    alpha3Code: 'PRT',
    numericCode: '620',
    topLevelDomain: '.pt',
    currencyCode: '',
  },
  {
    name: 'Puerto Rico',
    officialName: 'The Commonwealth of Puerto Rico',
    sovereignty: 'United States',
    code: 'PR',
    alpha3Code: 'PRI',
    numericCode: '630',
    topLevelDomain: '.pr',
    currencyCode: '',
  },
  {
    name: 'Qatar',
    officialName: 'The State of Qatar',
    sovereignty: 'UN member state',
    code: 'QA',
    alpha3Code: 'QAT',
    numericCode: '634',
    topLevelDomain: '.qa',
    currencyCode: '',
  },
  {
    name: 'Réunion',
    officialName: 'Réunion',
    sovereignty: 'France',
    code: 'RE',
    alpha3Code: 'REU',
    numericCode: '638',
    topLevelDomain: '.re',
    currencyCode: '',
  },
  {
    name: 'Romania',
    officialName: 'Romania',
    sovereignty: 'UN member state',
    code: 'RO',
    alpha3Code: 'ROU',
    numericCode: '642',
    topLevelDomain: '.ro',
    currencyCode: '',
  },
  {
    name: 'Russian Federation',
    officialName: 'The Russian Federation',
    sovereignty: 'UN member state',
    code: 'RU',
    alpha3Code: 'RUS',
    numericCode: '643',
    topLevelDomain: '.ru',
    currencyCode: '',
  },
  {
    name: 'Rwanda',
    officialName: 'The Republic of Rwanda',
    sovereignty: 'UN member state',
    code: 'RW',
    alpha3Code: 'RWA',
    numericCode: '646',
    topLevelDomain: '.rw',
    currencyCode: '',
  },
  {
    name: 'Saint Barthélemy',
    officialName: 'The Collectivity of Saint-Barthélemy',
    sovereignty: 'France',
    code: 'BL',
    alpha3Code: 'BLM',
    numericCode: '652',
    topLevelDomain: '.bl',
    currencyCode: '',
  },
  {
    name: 'Saint Helena Ascension Island Tristan da Cunha',
    officialName: 'Saint Helena, Ascension and Tristan da Cunha',
    sovereignty: 'United Kingdom',
    code: 'SH',
    alpha3Code: 'SHN',
    numericCode: '654',
    topLevelDomain: '.sh',
    currencyCode: '',
  },
  {
    name: 'Saint Kitts and Nevis',
    officialName: 'Saint Kitts and Nevis',
    sovereignty: 'UN member state',
    code: 'KN',
    alpha3Code: 'KNA',
    numericCode: '659',
    topLevelDomain: '.kn',
    currencyCode: '',
  },
  {
    name: 'Saint Lucia',
    officialName: 'Saint Lucia',
    sovereignty: 'UN member state',
    code: 'LC',
    alpha3Code: 'LCA',
    numericCode: '662',
    topLevelDomain: '.lc',
    currencyCode: '',
  },
  {
    name: 'Saint Martin',
    officialName: 'The Collectivity of Saint-Martin',
    sovereignty: 'France',
    code: 'MF',
    alpha3Code: 'MAF',
    numericCode: '663',
    topLevelDomain: '.mf',
    currencyCode: '',
  },
  {
    name: 'Saint Pierre and Miquelon',
    officialName: 'The Overseas Collectivity of Saint-Pierre and Miquelon',
    sovereignty: 'France',
    code: 'PM',
    alpha3Code: 'SPM',
    numericCode: '666',
    topLevelDomain: '.pm',
    currencyCode: '',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    officialName: 'Saint Vincent and the Grenadines',
    sovereignty: 'UN member state',
    code: 'VC',
    alpha3Code: 'VCT',
    numericCode: '670',
    topLevelDomain: '.vc',
    currencyCode: '',
  },
  {
    name: 'Samoa',
    officialName: 'The Independent State of Samoa',
    sovereignty: 'UN member state',
    code: 'WS',
    alpha3Code: 'WSM',
    numericCode: '882',
    topLevelDomain: '.ws',
    currencyCode: '',
  },
  {
    name: 'San Marino',
    officialName: 'The Republic of San Marino',
    sovereignty: 'UN member state',
    code: 'SM',
    alpha3Code: 'SMR',
    numericCode: '674',
    topLevelDomain: '.sm',
    currencyCode: '',
  },
  {
    name: 'Sao Tome and Principe',
    officialName: 'The Democratic Republic of São Tomé and Príncipe',
    sovereignty: 'UN member state',
    code: 'ST',
    alpha3Code: 'STP',
    numericCode: '678',
    topLevelDomain: '.st',
    currencyCode: '',
  },
  {
    name: 'Saudi Arabia',
    officialName: 'The Kingdom of Saudi Arabia',
    sovereignty: 'UN member state',
    code: 'SA',
    alpha3Code: 'SAU',
    numericCode: '682',
    topLevelDomain: '.sa',
    currencyCode: '',
  },
  {
    name: 'Senegal',
    officialName: 'The Republic of Senegal',
    sovereignty: 'UN member state',
    code: 'SN',
    alpha3Code: 'SEN',
    numericCode: '686',
    topLevelDomain: '.sn',
    currencyCode: '',
  },
  {
    name: 'Serbia',
    officialName: 'The Republic of Serbia',
    sovereignty: 'UN member state',
    code: 'RS',
    alpha3Code: 'SRB',
    numericCode: '688',
    topLevelDomain: '.rs',
    currencyCode: '',
  },
  {
    name: 'Seychelles',
    officialName: 'The Republic of Seychelles',
    sovereignty: 'UN member state',
    code: 'SC',
    alpha3Code: 'SYC',
    numericCode: '690',
    topLevelDomain: '.sc',
    currencyCode: '',
  },
  {
    name: 'Sierra Leone',
    officialName: 'The Republic of Sierra Leone',
    sovereignty: 'UN member state',
    code: 'SL',
    alpha3Code: 'SLE',
    numericCode: '694',
    topLevelDomain: '.sl',
    currencyCode: '',
  },
  {
    name: 'Singapore',
    officialName: 'The Republic of Singapore',
    sovereignty: 'UN member state',
    code: 'SG',
    alpha3Code: 'SGP',
    numericCode: '702',
    topLevelDomain: '.sg',
    currencyCode: '',
  },
  {
    name: 'Sint Maarten',
    officialName: 'Sint Maarten',
    sovereignty: 'Netherlands',
    code: 'SX',
    alpha3Code: 'SXM',
    numericCode: '534',
    topLevelDomain: '.sx',
    currencyCode: '',
  },
  {
    name: 'Slovakia',
    officialName: 'The Slovak Republic',
    sovereignty: 'UN member state',
    code: 'SK',
    alpha3Code: 'SVK',
    numericCode: '703',
    topLevelDomain: '.sk',
    currencyCode: '',
  },
  {
    name: 'Slovenia',
    officialName: 'The Republic of Slovenia',
    sovereignty: 'UN member state',
    code: 'SI',
    alpha3Code: 'SVN',
    numericCode: '705',
    topLevelDomain: '.si',
    currencyCode: '',
  },
  {
    name: 'Solomon Islands',
    officialName: 'The Solomon Islands',
    sovereignty: 'UN member state',
    code: 'SB',
    alpha3Code: 'SLB',
    numericCode: '090',
    topLevelDomain: '.sb',
    currencyCode: '',
  },
  {
    name: 'Somalia',
    officialName: 'The Federal Republic of Somalia',
    sovereignty: 'UN member state',
    code: 'SO',
    alpha3Code: 'SOM',
    numericCode: '706',
    topLevelDomain: '.so',
    currencyCode: '',
  },
  {
    name: 'South Africa',
    officialName: 'The Republic of South Africa',
    sovereignty: 'UN member state',
    code: 'ZA',
    alpha3Code: 'ZAF',
    numericCode: '710',
    topLevelDomain: '.za',
    currencyCode: '',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    officialName: 'South Georgia and the South Sandwich Islands',
    sovereignty: 'United Kingdom',
    code: 'GS',
    alpha3Code: 'SGS',
    numericCode: '239',
    topLevelDomain: '.gs',
    currencyCode: '',
  },
  {
    name: 'South Sudan',
    officialName: 'The Republic of South Sudan',
    sovereignty: 'UN member state',
    code: 'SS',
    alpha3Code: 'SSD',
    numericCode: '728',
    topLevelDomain: '.ss',
    currencyCode: '',
  },
  {
    name: 'Spain',
    officialName: 'The Kingdom of Spain',
    sovereignty: 'UN member state',
    code: 'ES',
    alpha3Code: 'ESP',
    numericCode: '724',
    topLevelDomain: '.es',
    currencyCode: '',
  },
  {
    name: 'Sri Lanka',
    officialName: 'The Democratic Socialist Republic of Sri Lanka',
    sovereignty: 'UN member state',
    code: 'LK',
    alpha3Code: 'LKA',
    numericCode: '144',
    topLevelDomain: '.lk',
    currencyCode: '',
  },
  {
    name: 'Sudan',
    officialName: 'The Republic of the Sudan',
    sovereignty: 'UN member state',
    code: 'SD',
    alpha3Code: 'SDN',
    numericCode: '729',
    topLevelDomain: '.sd',
    currencyCode: '',
  },
  {
    name: 'Suriname',
    officialName: 'The Republic of Suriname',
    sovereignty: 'UN member state',
    code: 'SR',
    alpha3Code: 'SUR',
    numericCode: '740',
    topLevelDomain: '.sr',
    currencyCode: '',
  },
  {
    name: 'Svalbard Jan Mayen',
    officialName: 'Svalbard and Jan Mayen',
    sovereignty: 'Norway',
    code: 'SJ',
    alpha3Code: 'SJM',
    numericCode: '744',
    topLevelDomain: '',
    currencyCode: '',
  },
  {
    name: 'Sweden',
    officialName: 'The Kingdom of Sweden',
    sovereignty: 'UN member state',
    code: 'SE',
    alpha3Code: 'SWE',
    numericCode: '752',
    topLevelDomain: '.se',
    currencyCode: '',
  },
  {
    name: 'Switzerland',
    officialName: 'The Swiss Confederation',
    sovereignty: 'UN member state',
    code: 'CH',
    alpha3Code: 'CHE',
    numericCode: '756',
    topLevelDomain: '.ch',
    currencyCode: '',
  },
  {
    name: 'Syrian Arab Republic',
    officialName: 'The Syrian Arab Republic',
    sovereignty: 'UN member state',
    code: 'SY',
    alpha3Code: 'SYR',
    numericCode: '760',
    topLevelDomain: '.sy',
    currencyCode: '',
  },
  {
    name: 'Taiwan',
    officialName: 'The Republic of China',
    sovereignty: 'Disputed',
    code: 'TW',
    alpha3Code: 'TWN',
    numericCode: '158',
    topLevelDomain: '.tw',
    currencyCode: '',
  },
  {
    name: 'Tajikistan',
    officialName: 'The Republic of Tajikistan',
    sovereignty: 'UN member state',
    code: 'TJ',
    alpha3Code: 'TJK',
    numericCode: '762',
    topLevelDomain: '.tj',
    currencyCode: '',
  },
  {
    name: 'Tanzania, the United Republic of',
    officialName: 'The United Republic of Tanzania',
    sovereignty: 'UN member state',
    code: 'TZ',
    alpha3Code: 'TZA',
    numericCode: '834',
    topLevelDomain: '.tz',
    currencyCode: '',
  },
  {
    name: 'Thailand',
    officialName: 'The Kingdom of Thailand',
    sovereignty: 'UN member state',
    code: 'TH',
    alpha3Code: 'THA',
    numericCode: '764',
    topLevelDomain: '.th',
    currencyCode: '',
  },
  {
    name: 'Timor-Leste',
    officialName: 'The Democratic Republic of Timor-Leste',
    sovereignty: 'UN member state',
    code: 'TL',
    alpha3Code: 'TLS',
    numericCode: '626',
    topLevelDomain: '.tl',
    currencyCode: '',
  },
  {
    name: 'Togo',
    officialName: 'The Togolese Republic',
    sovereignty: 'UN member state',
    code: 'TG',
    alpha3Code: 'TGO',
    numericCode: '768',
    topLevelDomain: '.tg',
    currencyCode: '',
  },
  {
    name: 'Tokelau',
    officialName: 'Tokelau',
    sovereignty: 'New Zealand',
    code: 'TK',
    alpha3Code: 'TKL',
    numericCode: '772',
    topLevelDomain: '.tk',
    currencyCode: '',
  },
  {
    name: 'Tonga',
    officialName: 'The Kingdom of Tonga',
    sovereignty: 'UN member state',
    code: 'TO',
    alpha3Code: 'TON',
    numericCode: '776',
    topLevelDomain: '.to',
    currencyCode: '',
  },
  {
    name: 'Trinidad and Tobago',
    officialName: 'The Republic of Trinidad and Tobago',
    sovereignty: 'UN member state',
    code: 'TT',
    alpha3Code: 'TTO',
    numericCode: '780',
    topLevelDomain: '.tt',
    currencyCode: '',
  },
  {
    name: 'Tunisia',
    officialName: 'The Republic of Tunisia',
    sovereignty: 'UN member state',
    code: 'TN',
    alpha3Code: 'TUN',
    numericCode: '788',
    topLevelDomain: '.tn',
    currencyCode: '',
  },
  {
    name: 'Turkey',
    officialName: 'The Republic of Turkey',
    sovereignty: 'UN member state',
    code: 'TR',
    alpha3Code: 'TUR',
    numericCode: '792',
    topLevelDomain: '.tr',
    currencyCode: '',
  },
  {
    name: 'Turkmenistan',
    officialName: 'Turkmenistan',
    sovereignty: 'UN member state',
    code: 'TM',
    alpha3Code: 'TKM',
    numericCode: '795',
    topLevelDomain: '.tm',
    currencyCode: '',
  },
  {
    name: 'Turks and Caicos Islands',
    officialName: 'The Turks and Caicos Islands',
    sovereignty: 'United Kingdom',
    code: 'TC',
    alpha3Code: 'TCA',
    numericCode: '796',
    topLevelDomain: '.tc',
    currencyCode: '',
  },
  {
    name: 'Tuvalu',
    officialName: 'Tuvalu',
    sovereignty: 'UN member state',
    code: 'TV',
    alpha3Code: 'TUV',
    numericCode: '798',
    topLevelDomain: '.tv',
    currencyCode: '',
  },
  {
    name: 'Uganda',
    officialName: 'The Republic of Uganda',
    sovereignty: 'UN member state',
    code: 'UG',
    alpha3Code: 'UGA',
    numericCode: '800',
    topLevelDomain: '.ug',
    currencyCode: '',
  },
  {
    name: 'Ukraine',
    officialName: 'Ukraine',
    sovereignty: 'UN member state',
    code: 'UA',
    alpha3Code: 'UKR',
    numericCode: '804',
    topLevelDomain: '.ua',
    currencyCode: '',
  },
  {
    name: 'United Arab Emirates',
    officialName: 'The United Arab Emirates',
    sovereignty: 'UN member state',
    code: 'AE',
    alpha3Code: 'ARE',
    numericCode: '784',
    topLevelDomain: '.ae',
    currencyCode: '',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    officialName: 'The United Kingdom of Great Britain and Northern Ireland',
    sovereignty: 'UN member state',
    code: 'GB',
    alpha3Code: 'GBR',
    numericCode: '826',
    topLevelDomain: '.gb .uk',
    currencyCode: '',
  },
  {
    name: 'United States Minor Outlying Islands',
    officialName:
      'Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island',
    sovereignty: 'United States',
    code: 'UM',
    alpha3Code: 'UMI',
    numericCode: '581',
    topLevelDomain: '',
    currencyCode: '',
  },
  {
    name: 'United States of America',
    officialName: 'The United States of America',
    sovereignty: 'UN member state',
    code: 'US',
    alpha3Code: 'USA',
    numericCode: '840',
    topLevelDomain: '.us',
    currencyCode: '',
  },
  {
    name: 'Uruguay',
    officialName: 'The Oriental Republic of Uruguay',
    sovereignty: 'UN member state',
    code: 'UY',
    alpha3Code: 'URY',
    numericCode: '858',
    topLevelDomain: '.uy',
    currencyCode: '',
  },
  {
    name: 'Uzbekistan',
    officialName: 'The Republic of Uzbekistan',
    sovereignty: 'UN member state',
    code: 'UZ',
    alpha3Code: 'UZB',
    numericCode: '860',
    topLevelDomain: '.uz',
    currencyCode: '',
  },
  {
    name: 'Vanuatu',
    officialName: 'The Republic of Vanuatu',
    sovereignty: 'UN member state',
    code: 'VU',
    alpha3Code: 'VUT',
    numericCode: '548',
    topLevelDomain: '.vu',
    currencyCode: '',
  },
  {
    name: 'Venezuela',
    officialName: 'The Bolivarian Republic of Venezuela',
    sovereignty: 'UN member state',
    code: 'VE',
    alpha3Code: 'VEN',
    numericCode: '862',
    topLevelDomain: '.ve',
    currencyCode: '',
  },
  {
    name: 'Viet Nam',
    officialName: 'The Socialist Republic of Viet Nam',
    sovereignty: 'UN member state',
    code: 'VN',
    alpha3Code: 'VNM',
    numericCode: '704',
    topLevelDomain: '.vn',
    currencyCode: '',
  },
  {
    name: 'Virgin Islands',
    officialName: 'The Virgin Islands',
    sovereignty: 'United Kingdom',
    code: 'VG',
    alpha3Code: 'VGB',
    numericCode: '092',
    topLevelDomain: '.vg',
    currencyCode: '',
  },
  {
    name: 'Virgin Islands',
    officialName: 'The Virgin Islands of the United States',
    sovereignty: 'United States',
    code: 'VI',
    alpha3Code: 'VIR',
    numericCode: '850',
    topLevelDomain: '.vi',
    currencyCode: '',
  },
  {
    name: 'Wallis and Futuna',
    officialName: 'The Territory of the Wallis and Futuna Islands',
    sovereignty: 'France',
    code: 'WF',
    alpha3Code: 'WLF',
    numericCode: '876',
    topLevelDomain: '.wf',
    currencyCode: '',
  },
  {
    name: 'Western Sahara',
    officialName: 'The Sahrawi Arab Democratic Republic',
    sovereignty: 'Disputed',
    code: 'EH',
    alpha3Code: 'ESH',
    numericCode: '732',
    topLevelDomain: '',
    currencyCode: '',
  },
  {
    name: 'Yemen',
    officialName: 'The Republic of Yemen',
    sovereignty: 'UN member state',
    code: 'YE',
    alpha3Code: 'YEM',
    numericCode: '887',
    topLevelDomain: '.ye',
    currencyCode: '',
  },
  {
    name: 'Zambia',
    officialName: 'The Republic of Zambia',
    sovereignty: 'UN member state',
    code: 'ZM',
    alpha3Code: 'ZMB',
    numericCode: '894',
    topLevelDomain: '.zm',
    currencyCode: '',
  },
  {
    name: 'Zimbabwe',
    officialName: 'The Republic of Zimbabwe',
    sovereignty: 'UN member state',
    code: 'ZW',
    alpha3Code: 'ZWE',
    numericCode: '716',
    topLevelDomain: '.zw',
    currencyCode: '',
  },
];

export default countryDataList;
