import { CountryData } from './CountryData';
export const countryDataList: CountryData[] = [
  {
    name: 'Afghanistan',
    code: 'AF',
    alpha3Code: 'AFG',
    numericCode: '004',
    topLevelDomains: ['.af'],
    currencyCodes: ['AFN'],
  },
  {
    name: 'Åland Islands',
    code: 'AX',
    alpha3Code: 'ALA',
    numericCode: '248',
    topLevelDomains: ['.ax'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Albania',
    code: 'AL',
    alpha3Code: 'ALB',
    numericCode: '008',
    topLevelDomains: ['.al'],
    currencyCodes: ['ALL'],
  },
  {
    name: 'Algeria',
    code: 'DZ',
    alpha3Code: 'DZA',
    numericCode: '012',
    topLevelDomains: ['.dz'],
    currencyCodes: ['DZD'],
  },
  {
    name: 'American Samoa',
    code: 'AS',
    alpha3Code: 'ASM',
    numericCode: '016',
    topLevelDomains: ['.as'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Andorra',
    code: 'AD',
    alpha3Code: 'AND',
    numericCode: '020',
    topLevelDomains: ['.ad'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Angola',
    code: 'AO',
    alpha3Code: 'AGO',
    numericCode: '024',
    topLevelDomains: ['.ao'],
    currencyCodes: ['AOA'],
  },
  {
    name: 'Anguilla',
    code: 'AI',
    alpha3Code: 'AIA',
    numericCode: '660',
    topLevelDomains: ['.ai'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    alpha3Code: 'ATA',
    numericCode: '010',
    topLevelDomains: ['.aq'],
    currencyCodes: [],
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    alpha3Code: 'ATG',
    numericCode: '028',
    topLevelDomains: ['.ag'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Argentina',
    code: 'AR',
    alpha3Code: 'ARG',
    numericCode: '032',
    topLevelDomains: ['.ar'],
    currencyCodes: ['ARS'],
  },
  {
    name: 'Armenia',
    code: 'AM',
    alpha3Code: 'ARM',
    numericCode: '051',
    topLevelDomains: ['.am'],
    currencyCodes: ['AMD'],
  },
  {
    name: 'Aruba',
    code: 'AW',
    alpha3Code: 'ABW',
    numericCode: '533',
    topLevelDomains: ['.aw'],
    currencyCodes: ['AWG'],
  },
  {
    name: 'Australia',
    code: 'AU',
    alpha3Code: 'AUS',
    numericCode: '036',
    topLevelDomains: ['.au'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Austria',
    code: 'AT',
    alpha3Code: 'AUT',
    numericCode: '040',
    topLevelDomains: ['.at'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    alpha3Code: 'AZE',
    numericCode: '031',
    topLevelDomains: ['.az'],
    currencyCodes: ['AZN'],
  },
  {
    name: 'Bahamas',
    code: 'BS',
    alpha3Code: 'BHS',
    numericCode: '044',
    topLevelDomains: ['.bs'],
    currencyCodes: ['BSD'],
  },
  {
    name: 'Bahrain',
    code: 'BH',
    alpha3Code: 'BHR',
    numericCode: '048',
    topLevelDomains: ['.bh'],
    currencyCodes: ['BHD'],
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    alpha3Code: 'BGD',
    numericCode: '050',
    topLevelDomains: ['.bd'],
    currencyCodes: ['BDT'],
  },
  {
    name: 'Barbados',
    code: 'BB',
    alpha3Code: 'BRB',
    numericCode: '052',
    topLevelDomains: ['.bb'],
    currencyCodes: ['BBD'],
  },
  {
    name: 'Belarus',
    code: 'BY',
    alpha3Code: 'BLR',
    numericCode: '112',
    topLevelDomains: ['.by'],
    currencyCodes: ['BYN'],
  },
  {
    name: 'Belgium',
    code: 'BE',
    alpha3Code: 'BEL',
    numericCode: '056',
    topLevelDomains: ['.be'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Belize',
    code: 'BZ',
    alpha3Code: 'BLZ',
    numericCode: '084',
    topLevelDomains: ['.bz'],
    currencyCodes: ['BZD'],
  },
  {
    name: 'Benin',
    code: 'BJ',
    alpha3Code: 'BEN',
    numericCode: '204',
    topLevelDomains: ['.bj'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Bermuda',
    code: 'BM',
    alpha3Code: 'BMU',
    numericCode: '060',
    topLevelDomains: ['.bm'],
    currencyCodes: ['BMD'],
  },
  {
    name: 'Bhutan',
    code: 'BT',
    alpha3Code: 'BTN',
    numericCode: '064',
    topLevelDomains: ['.bt'],
    currencyCodes: ['BTN', 'INR'],
  },
  {
    name: 'Bolivia (Plurinational State of)',
    code: 'BO',
    alpha3Code: 'BOL',
    numericCode: '068',
    topLevelDomains: ['.bo'],
    currencyCodes: [],
  },
  {
    name: 'Bonaire Sint Eustatius Saba',
    code: 'BQ',
    alpha3Code: 'BES',
    numericCode: '535',
    topLevelDomains: ['.bq', '.nl'],
    currencyCodes: [],
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    alpha3Code: 'BIH',
    numericCode: '070',
    topLevelDomains: ['.ba'],
    currencyCodes: ['BAM'],
  },
  {
    name: 'Botswana',
    code: 'BW',
    alpha3Code: 'BWA',
    numericCode: '072',
    topLevelDomains: ['.bw'],
    currencyCodes: ['BWP'],
  },
  {
    name: 'Bouvet Island',
    code: 'BV',
    alpha3Code: 'BVT',
    numericCode: '074',
    topLevelDomains: [''],
    currencyCodes: ['NOK'],
  },
  {
    name: 'Brazil',
    code: 'BR',
    alpha3Code: 'BRA',
    numericCode: '076',
    topLevelDomains: ['.br'],
    currencyCodes: ['BRL'],
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    alpha3Code: 'IOT',
    numericCode: '086',
    topLevelDomains: ['.io'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    alpha3Code: 'BRN',
    numericCode: '096',
    topLevelDomains: ['.bn'],
    currencyCodes: [],
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    alpha3Code: 'BGR',
    numericCode: '100',
    topLevelDomains: ['.bg'],
    currencyCodes: ['BGN'],
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    alpha3Code: 'BFA',
    numericCode: '854',
    topLevelDomains: ['.bf'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Burundi',
    code: 'BI',
    alpha3Code: 'BDI',
    numericCode: '108',
    topLevelDomains: ['.bi'],
    currencyCodes: ['BIF'],
  },
  {
    name: 'Cabo Verde',
    code: 'CV',
    alpha3Code: 'CPV',
    numericCode: '132',
    topLevelDomains: ['.cv'],
    currencyCodes: ['CVE'],
  },
  {
    name: 'Cambodia',
    code: 'KH',
    alpha3Code: 'KHM',
    numericCode: '116',
    topLevelDomains: ['.kh'],
    currencyCodes: ['KHR'],
  },
  {
    name: 'Cameroon',
    code: 'CM',
    alpha3Code: 'CMR',
    numericCode: '120',
    topLevelDomains: ['.cm'],
    currencyCodes: ['XAF'],
  },
  {
    name: 'Canada',
    code: 'CA',
    alpha3Code: 'CAN',
    numericCode: '124',
    topLevelDomains: ['.ca'],
    currencyCodes: ['CAD'],
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    alpha3Code: 'CYM',
    numericCode: '136',
    topLevelDomains: ['.ky'],
    currencyCodes: ['KYD'],
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    alpha3Code: 'CAF',
    numericCode: '140',
    topLevelDomains: ['.cf'],
    currencyCodes: ['XAF'],
  },
  {
    name: 'Chad',
    code: 'TD',
    alpha3Code: 'TCD',
    numericCode: '148',
    topLevelDomains: ['.td'],
    currencyCodes: ['XAF'],
  },
  {
    name: 'Chile',
    code: 'CL',
    alpha3Code: 'CHL',
    numericCode: '152',
    topLevelDomains: ['.cl'],
    currencyCodes: ['CLF', 'CLP'],
  },
  {
    name: 'China',
    code: 'CN',
    alpha3Code: 'CHN',
    numericCode: '156',
    topLevelDomains: ['.cn'],
    currencyCodes: ['CNY'],
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    alpha3Code: 'CXR',
    numericCode: '162',
    topLevelDomains: ['.cx'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    alpha3Code: 'CCK',
    numericCode: '166',
    topLevelDomains: ['.cc'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Colombia',
    code: 'CO',
    alpha3Code: 'COL',
    numericCode: '170',
    topLevelDomains: ['.co'],
    currencyCodes: ['COP', 'COU'],
  },
  {
    name: 'Comoros',
    code: 'KM',
    alpha3Code: 'COM',
    numericCode: '174',
    topLevelDomains: ['.km'],
    currencyCodes: ['KMF'],
  },
  {
    name: 'Congo (the Democratic Republic of the)',
    code: 'CD',
    alpha3Code: 'COD',
    numericCode: '180',
    topLevelDomains: ['.cd'],
    currencyCodes: [],
  },
  {
    name: 'Congo',
    code: 'CG',
    alpha3Code: 'COG',
    numericCode: '178',
    topLevelDomains: ['.cg'],
    currencyCodes: ['CDF', 'XAF'],
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    alpha3Code: 'COK',
    numericCode: '184',
    topLevelDomains: ['.ck'],
    currencyCodes: ['NZD'],
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    alpha3Code: 'CRI',
    numericCode: '188',
    topLevelDomains: ['.cr'],
    currencyCodes: ['CRC'],
  },
  {
    name: "Côte d'Ivoire",
    code: 'CI',
    alpha3Code: 'CIV',
    numericCode: '384',
    topLevelDomains: ['.ci'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Croatia',
    code: 'HR',
    alpha3Code: 'HRV',
    numericCode: '191',
    topLevelDomains: ['.hr'],
    currencyCodes: ['HRK'],
  },
  {
    name: 'Cuba',
    code: 'CU',
    alpha3Code: 'CUB',
    numericCode: '192',
    topLevelDomains: ['.cu'],
    currencyCodes: ['CUC', 'CUP'],
  },
  {
    name: 'Curaçao',
    code: 'CW',
    alpha3Code: 'CUW',
    numericCode: '531',
    topLevelDomains: ['.cw'],
    currencyCodes: ['ANG'],
  },
  {
    name: 'Cyprus',
    code: 'CY',
    alpha3Code: 'CYP',
    numericCode: '196',
    topLevelDomains: ['.cy'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Czechia',
    code: 'CZ',
    alpha3Code: 'CZE',
    numericCode: '203',
    topLevelDomains: ['.cz'],
    currencyCodes: ['CZK'],
  },
  {
    name: 'Denmark',
    code: 'DK',
    alpha3Code: 'DNK',
    numericCode: '208',
    topLevelDomains: ['.dk'],
    currencyCodes: ['DKK'],
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    alpha3Code: 'DJI',
    numericCode: '262',
    topLevelDomains: ['.dj'],
    currencyCodes: ['DJF'],
  },
  {
    name: 'Dominica',
    code: 'DM',
    alpha3Code: 'DMA',
    numericCode: '212',
    topLevelDomains: ['.dm'],
    currencyCodes: ['DOP', 'XCD'],
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    alpha3Code: 'DOM',
    numericCode: '214',
    topLevelDomains: ['.do'],
    currencyCodes: ['DOP'],
  },
  {
    name: 'Ecuador',
    code: 'EC',
    alpha3Code: 'ECU',
    numericCode: '218',
    topLevelDomains: ['.ec'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Egypt',
    code: 'EG',
    alpha3Code: 'EGY',
    numericCode: '818',
    topLevelDomains: ['.eg'],
    currencyCodes: ['EGP'],
  },
  {
    name: 'El Salvador',
    code: 'SV',
    alpha3Code: 'SLV',
    numericCode: '222',
    topLevelDomains: ['.sv'],
    currencyCodes: ['SVC', 'USD'],
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    alpha3Code: 'GNQ',
    numericCode: '226',
    topLevelDomains: ['.gq'],
    currencyCodes: ['XAF'],
  },
  {
    name: 'Eritrea',
    code: 'ER',
    alpha3Code: 'ERI',
    numericCode: '232',
    topLevelDomains: ['.er'],
    currencyCodes: ['ERN'],
  },
  {
    name: 'Estonia',
    code: 'EE',
    alpha3Code: 'EST',
    numericCode: '233',
    topLevelDomains: ['.ee'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    alpha3Code: 'SWZ',
    numericCode: '748',
    topLevelDomains: ['.sz'],
    currencyCodes: ['SZL', 'ZAR'],
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    alpha3Code: 'ETH',
    numericCode: '231',
    topLevelDomains: ['.et'],
    currencyCodes: ['ETB'],
  },
  {
    name: 'Falkland Islands',
    code: 'FK',
    alpha3Code: 'FLK',
    numericCode: '238',
    topLevelDomains: ['.fk'],
    currencyCodes: ['FKP'],
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    alpha3Code: 'FRO',
    numericCode: '234',
    topLevelDomains: ['.fo'],
    currencyCodes: ['DKK'],
  },
  {
    name: 'Fiji',
    code: 'FJ',
    alpha3Code: 'FJI',
    numericCode: '242',
    topLevelDomains: ['.fj'],
    currencyCodes: ['FJD'],
  },
  {
    name: 'Finland',
    code: 'FI',
    alpha3Code: 'FIN',
    numericCode: '246',
    topLevelDomains: ['.fi'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'France',
    code: 'FR',
    alpha3Code: 'FRA',
    numericCode: '250',
    topLevelDomains: ['.fr'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'French Guiana',
    code: 'GF',
    alpha3Code: 'GUF',
    numericCode: '254',
    topLevelDomains: ['.gf'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    alpha3Code: 'PYF',
    numericCode: '258',
    topLevelDomains: ['.pf'],
    currencyCodes: ['XPF'],
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    alpha3Code: 'ATF',
    numericCode: '260',
    topLevelDomains: ['.tf'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Gabon',
    code: 'GA',
    alpha3Code: 'GAB',
    numericCode: '266',
    topLevelDomains: ['.ga'],
    currencyCodes: ['XAF'],
  },
  {
    name: 'Gambia',
    code: 'GM',
    alpha3Code: 'GMB',
    numericCode: '270',
    topLevelDomains: ['.gm'],
    currencyCodes: ['GMD'],
  },
  {
    name: 'Georgia',
    code: 'GE',
    alpha3Code: 'GEO',
    numericCode: '268',
    topLevelDomains: ['.ge'],
    currencyCodes: ['GEL'],
  },
  {
    name: 'Germany',
    code: 'DE',
    alpha3Code: 'DEU',
    numericCode: '276',
    topLevelDomains: ['.de'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Ghana',
    code: 'GH',
    alpha3Code: 'GHA',
    numericCode: '288',
    topLevelDomains: ['.gh'],
    currencyCodes: ['GHS'],
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    alpha3Code: 'GIB',
    numericCode: '292',
    topLevelDomains: ['.gi'],
    currencyCodes: ['GIP'],
  },
  {
    name: 'Greece',
    code: 'GR',
    alpha3Code: 'GRC',
    numericCode: '300',
    topLevelDomains: ['.gr'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Greenland',
    code: 'GL',
    alpha3Code: 'GRL',
    numericCode: '304',
    topLevelDomains: ['.gl'],
    currencyCodes: ['DKK'],
  },
  {
    name: 'Grenada',
    code: 'GD',
    alpha3Code: 'GRD',
    numericCode: '308',
    topLevelDomains: ['.gd'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    alpha3Code: 'GLP',
    numericCode: '312',
    topLevelDomains: ['.gp'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Guam',
    code: 'GU',
    alpha3Code: 'GUM',
    numericCode: '316',
    topLevelDomains: ['.gu'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Guatemala',
    code: 'GT',
    alpha3Code: 'GTM',
    numericCode: '320',
    topLevelDomains: ['.gt'],
    currencyCodes: ['GTQ'],
  },
  {
    name: 'Guernsey',
    code: 'GG',
    alpha3Code: 'GGY',
    numericCode: '831',
    topLevelDomains: ['.gg'],
    currencyCodes: ['GBP'],
  },
  {
    name: 'Guinea',
    code: 'GN',
    alpha3Code: 'GIN',
    numericCode: '324',
    topLevelDomains: ['.gn'],
    currencyCodes: ['GNF', 'PGK', 'XAF', 'XOF'],
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    alpha3Code: 'GNB',
    numericCode: '624',
    topLevelDomains: ['.gw'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Guyana',
    code: 'GY',
    alpha3Code: 'GUY',
    numericCode: '328',
    topLevelDomains: ['.gy'],
    currencyCodes: ['GYD'],
  },
  {
    name: 'Haiti',
    code: 'HT',
    alpha3Code: 'HTI',
    numericCode: '332',
    topLevelDomains: ['.ht'],
    currencyCodes: ['HTG'],
  },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    alpha3Code: 'HMD',
    numericCode: '334',
    topLevelDomains: ['.hm'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Holy See',
    code: 'VA',
    alpha3Code: 'VAT',
    numericCode: '336',
    topLevelDomains: ['.va'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Honduras',
    code: 'HN',
    alpha3Code: 'HND',
    numericCode: '340',
    topLevelDomains: ['.hn'],
    currencyCodes: ['HNL'],
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    alpha3Code: 'HKG',
    numericCode: '344',
    topLevelDomains: ['.hk'],
    currencyCodes: ['HKD'],
  },
  {
    name: 'Hungary',
    code: 'HU',
    alpha3Code: 'HUN',
    numericCode: '348',
    topLevelDomains: ['.hu'],
    currencyCodes: ['HUF'],
  },
  {
    name: 'Iceland',
    code: 'IS',
    alpha3Code: 'ISL',
    numericCode: '352',
    topLevelDomains: ['.is'],
    currencyCodes: ['ISK'],
  },
  {
    name: 'India',
    code: 'IN',
    alpha3Code: 'IND',
    numericCode: '356',
    topLevelDomains: ['.in'],
    currencyCodes: ['INR', 'USD'],
  },
  {
    name: 'Indonesia',
    code: 'ID',
    alpha3Code: 'IDN',
    numericCode: '360',
    topLevelDomains: ['.id'],
    currencyCodes: ['IDR'],
  },
  {
    name: 'Iran (Islamic Republic of)',
    code: 'IR',
    alpha3Code: 'IRN',
    numericCode: '364',
    topLevelDomains: ['.ir'],
    currencyCodes: [],
  },
  {
    name: 'Iraq',
    code: 'IQ',
    alpha3Code: 'IRQ',
    numericCode: '368',
    topLevelDomains: ['.iq'],
    currencyCodes: ['IQD'],
  },
  {
    name: 'Ireland',
    code: 'IE',
    alpha3Code: 'IRL',
    numericCode: '372',
    topLevelDomains: ['.ie'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    alpha3Code: 'IMN',
    numericCode: '833',
    topLevelDomains: ['.im'],
    currencyCodes: ['GBP'],
  },
  {
    name: 'Israel',
    code: 'IL',
    alpha3Code: 'ISR',
    numericCode: '376',
    topLevelDomains: ['.il'],
    currencyCodes: ['ILS'],
  },
  {
    name: 'Italy',
    code: 'IT',
    alpha3Code: 'ITA',
    numericCode: '380',
    topLevelDomains: ['.it'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Jamaica',
    code: 'JM',
    alpha3Code: 'JAM',
    numericCode: '388',
    topLevelDomains: ['.jm'],
    currencyCodes: ['JMD'],
  },
  {
    name: 'Japan',
    code: 'JP',
    alpha3Code: 'JPN',
    numericCode: '392',
    topLevelDomains: ['.jp'],
    currencyCodes: ['JPY'],
  },
  {
    name: 'Jersey',
    code: 'JE',
    alpha3Code: 'JEY',
    numericCode: '832',
    topLevelDomains: ['.je'],
    currencyCodes: ['GBP'],
  },
  {
    name: 'Jordan',
    code: 'JO',
    alpha3Code: 'JOR',
    numericCode: '400',
    topLevelDomains: ['.jo'],
    currencyCodes: ['JOD'],
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    alpha3Code: 'KAZ',
    numericCode: '398',
    topLevelDomains: ['.kz'],
    currencyCodes: ['KZT'],
  },
  {
    name: 'Kenya',
    code: 'KE',
    alpha3Code: 'KEN',
    numericCode: '404',
    topLevelDomains: ['.ke'],
    currencyCodes: ['KES'],
  },
  {
    name: 'Kiribati',
    code: 'KI',
    alpha3Code: 'KIR',
    numericCode: '296',
    topLevelDomains: ['.ki'],
    currencyCodes: ['AUD'],
  },
  {
    name: "Korea (the Democratic People's Republic of)",
    code: 'KP',
    alpha3Code: 'PRK',
    numericCode: '408',
    topLevelDomains: ['.kp'],
    currencyCodes: [],
  },
  {
    name: 'Korea (the Republic of)',
    code: 'KR',
    alpha3Code: 'KOR',
    numericCode: '410',
    topLevelDomains: ['.kr'],
    currencyCodes: [],
  },
  {
    name: 'Kuwait',
    code: 'KW',
    alpha3Code: 'KWT',
    numericCode: '414',
    topLevelDomains: ['.kw'],
    currencyCodes: ['KWD'],
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    alpha3Code: 'KGZ',
    numericCode: '417',
    topLevelDomains: ['.kg'],
    currencyCodes: ['KGS'],
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    alpha3Code: 'LAO',
    numericCode: '418',
    topLevelDomains: ['.la'],
    currencyCodes: [],
  },
  {
    name: 'Latvia',
    code: 'LV',
    alpha3Code: 'LVA',
    numericCode: '428',
    topLevelDomains: ['.lv'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Lebanon',
    code: 'LB',
    alpha3Code: 'LBN',
    numericCode: '422',
    topLevelDomains: ['.lb'],
    currencyCodes: ['LBP'],
  },
  {
    name: 'Lesotho',
    code: 'LS',
    alpha3Code: 'LSO',
    numericCode: '426',
    topLevelDomains: ['.ls'],
    currencyCodes: ['LSL', 'ZAR'],
  },
  {
    name: 'Liberia',
    code: 'LR',
    alpha3Code: 'LBR',
    numericCode: '430',
    topLevelDomains: ['.lr'],
    currencyCodes: ['LRD'],
  },
  {
    name: 'Libya',
    code: 'LY',
    alpha3Code: 'LBY',
    numericCode: '434',
    topLevelDomains: ['.ly'],
    currencyCodes: ['LYD'],
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    alpha3Code: 'LIE',
    numericCode: '438',
    topLevelDomains: ['.li'],
    currencyCodes: ['CHF'],
  },
  {
    name: 'Lithuania',
    code: 'LT',
    alpha3Code: 'LTU',
    numericCode: '440',
    topLevelDomains: ['.lt'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    alpha3Code: 'LUX',
    numericCode: '442',
    topLevelDomains: ['.lu'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Macao',
    code: 'MO',
    alpha3Code: 'MAC',
    numericCode: '446',
    topLevelDomains: ['.mo'],
    currencyCodes: [],
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    alpha3Code: 'MKD',
    numericCode: '807',
    topLevelDomains: ['.mk'],
    currencyCodes: ['MKD'],
  },
  {
    name: 'Madagascar',
    code: 'MG',
    alpha3Code: 'MDG',
    numericCode: '450',
    topLevelDomains: ['.mg'],
    currencyCodes: ['MGA'],
  },
  {
    name: 'Malawi',
    code: 'MW',
    alpha3Code: 'MWI',
    numericCode: '454',
    topLevelDomains: ['.mw'],
    currencyCodes: ['MWK'],
  },
  {
    name: 'Malaysia',
    code: 'MY',
    alpha3Code: 'MYS',
    numericCode: '458',
    topLevelDomains: ['.my'],
    currencyCodes: ['MYR'],
  },
  {
    name: 'Maldives',
    code: 'MV',
    alpha3Code: 'MDV',
    numericCode: '462',
    topLevelDomains: ['.mv'],
    currencyCodes: ['MVR'],
  },
  {
    name: 'Mali',
    code: 'ML',
    alpha3Code: 'MLI',
    numericCode: '466',
    topLevelDomains: ['.ml'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Malta',
    code: 'MT',
    alpha3Code: 'MLT',
    numericCode: '470',
    topLevelDomains: ['.mt'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    alpha3Code: 'MHL',
    numericCode: '584',
    topLevelDomains: ['.mh'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Martinique',
    code: 'MQ',
    alpha3Code: 'MTQ',
    numericCode: '474',
    topLevelDomains: ['.mq'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Mauritania',
    code: 'MR',
    alpha3Code: 'MRT',
    numericCode: '478',
    topLevelDomains: ['.mr'],
    currencyCodes: ['MRU'],
  },
  {
    name: 'Mauritius',
    code: 'MU',
    alpha3Code: 'MUS',
    numericCode: '480',
    topLevelDomains: ['.mu'],
    currencyCodes: ['MUR'],
  },
  {
    name: 'Mayotte',
    code: 'YT',
    alpha3Code: 'MYT',
    numericCode: '175',
    topLevelDomains: ['.yt'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Mexico',
    code: 'MX',
    alpha3Code: 'MEX',
    numericCode: '484',
    topLevelDomains: ['.mx'],
    currencyCodes: ['MXN', 'MXV'],
  },
  {
    name: 'Micronesia (Federated States of)',
    code: 'FM',
    alpha3Code: 'FSM',
    numericCode: '583',
    topLevelDomains: ['.fm'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Moldova (the Republic of)',
    code: 'MD',
    alpha3Code: 'MDA',
    numericCode: '498',
    topLevelDomains: ['.md'],
    currencyCodes: [],
  },
  {
    name: 'Monaco',
    code: 'MC',
    alpha3Code: 'MCO',
    numericCode: '492',
    topLevelDomains: ['.mc'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Mongolia',
    code: 'MN',
    alpha3Code: 'MNG',
    numericCode: '496',
    topLevelDomains: ['.mn'],
    currencyCodes: ['MNT'],
  },
  {
    name: 'Montenegro',
    code: 'ME',
    alpha3Code: 'MNE',
    numericCode: '499',
    topLevelDomains: ['.me'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Montserrat',
    code: 'MS',
    alpha3Code: 'MSR',
    numericCode: '500',
    topLevelDomains: ['.ms'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Morocco',
    code: 'MA',
    alpha3Code: 'MAR',
    numericCode: '504',
    topLevelDomains: ['.ma'],
    currencyCodes: ['MAD'],
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    alpha3Code: 'MOZ',
    numericCode: '508',
    topLevelDomains: ['.mz'],
    currencyCodes: ['MZN'],
  },
  {
    name: 'Myanmar',
    code: 'MM',
    alpha3Code: 'MMR',
    numericCode: '104',
    topLevelDomains: ['.mm'],
    currencyCodes: ['MMK'],
  },
  {
    name: 'Namibia',
    code: 'NA',
    alpha3Code: 'NAM',
    numericCode: '516',
    topLevelDomains: ['.na'],
    currencyCodes: ['NAD', 'ZAR'],
  },
  {
    name: 'Nauru',
    code: 'NR',
    alpha3Code: 'NRU',
    numericCode: '520',
    topLevelDomains: ['.nr'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Nepal',
    code: 'NP',
    alpha3Code: 'NPL',
    numericCode: '524',
    topLevelDomains: ['.np'],
    currencyCodes: ['NPR'],
  },
  {
    name: 'Netherlands',
    code: 'NL',
    alpha3Code: 'NLD',
    numericCode: '528',
    topLevelDomains: ['.nl'],
    currencyCodes: ['EUR', 'USD'],
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    alpha3Code: 'NCL',
    numericCode: '540',
    topLevelDomains: ['.nc'],
    currencyCodes: ['XPF'],
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    alpha3Code: 'NZL',
    numericCode: '554',
    topLevelDomains: ['.nz'],
    currencyCodes: ['NZD'],
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    alpha3Code: 'NIC',
    numericCode: '558',
    topLevelDomains: ['.ni'],
    currencyCodes: ['NIO'],
  },
  {
    name: 'Niger',
    code: 'NE',
    alpha3Code: 'NER',
    numericCode: '562',
    topLevelDomains: ['.ne'],
    currencyCodes: ['NGN', 'XOF'],
  },
  {
    name: 'Nigeria',
    code: 'NG',
    alpha3Code: 'NGA',
    numericCode: '566',
    topLevelDomains: ['.ng'],
    currencyCodes: ['NGN'],
  },
  {
    name: 'Niue',
    code: 'NU',
    alpha3Code: 'NIU',
    numericCode: '570',
    topLevelDomains: ['.nu'],
    currencyCodes: ['NZD'],
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    alpha3Code: 'NFK',
    numericCode: '574',
    topLevelDomains: ['.nf'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    alpha3Code: 'MNP',
    numericCode: '580',
    topLevelDomains: ['.mp'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Norway',
    code: 'NO',
    alpha3Code: 'NOR',
    numericCode: '578',
    topLevelDomains: ['.no'],
    currencyCodes: ['NOK'],
  },
  {
    name: 'Oman',
    code: 'OM',
    alpha3Code: 'OMN',
    numericCode: '512',
    topLevelDomains: ['.om'],
    currencyCodes: ['OMR'],
  },
  {
    name: 'Pakistan',
    code: 'PK',
    alpha3Code: 'PAK',
    numericCode: '586',
    topLevelDomains: ['.pk'],
    currencyCodes: ['PKR'],
  },
  {
    name: 'Palau',
    code: 'PW',
    alpha3Code: 'PLW',
    numericCode: '585',
    topLevelDomains: ['.pw'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Palestine, State of',
    code: 'PS',
    alpha3Code: 'PSE',
    numericCode: '275',
    topLevelDomains: ['.ps'],
    currencyCodes: [],
  },
  {
    name: 'Panama',
    code: 'PA',
    alpha3Code: 'PAN',
    numericCode: '591',
    topLevelDomains: ['.pa'],
    currencyCodes: ['PAB', 'USD'],
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    alpha3Code: 'PNG',
    numericCode: '598',
    topLevelDomains: ['.pg'],
    currencyCodes: ['PGK'],
  },
  {
    name: 'Paraguay',
    code: 'PY',
    alpha3Code: 'PRY',
    numericCode: '600',
    topLevelDomains: ['.py'],
    currencyCodes: ['PYG'],
  },
  {
    name: 'Peru',
    code: 'PE',
    alpha3Code: 'PER',
    numericCode: '604',
    topLevelDomains: ['.pe'],
    currencyCodes: ['PEN'],
  },
  {
    name: 'Philippines',
    code: 'PH',
    alpha3Code: 'PHL',
    numericCode: '608',
    topLevelDomains: ['.ph'],
    currencyCodes: ['PHP'],
  },
  {
    name: 'Pitcairn',
    code: 'PN',
    alpha3Code: 'PCN',
    numericCode: '612',
    topLevelDomains: ['.pn'],
    currencyCodes: ['NZD'],
  },
  {
    name: 'Poland',
    code: 'PL',
    alpha3Code: 'POL',
    numericCode: '616',
    topLevelDomains: ['.pl'],
    currencyCodes: ['PLN'],
  },
  {
    name: 'Portugal',
    code: 'PT',
    alpha3Code: 'PRT',
    numericCode: '620',
    topLevelDomains: ['.pt'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    alpha3Code: 'PRI',
    numericCode: '630',
    topLevelDomains: ['.pr'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Qatar',
    code: 'QA',
    alpha3Code: 'QAT',
    numericCode: '634',
    topLevelDomains: ['.qa'],
    currencyCodes: ['QAR'],
  },
  {
    name: 'Réunion',
    code: 'RE',
    alpha3Code: 'REU',
    numericCode: '638',
    topLevelDomains: ['.re'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Romania',
    code: 'RO',
    alpha3Code: 'ROU',
    numericCode: '642',
    topLevelDomains: ['.ro'],
    currencyCodes: ['RON'],
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    alpha3Code: 'RUS',
    numericCode: '643',
    topLevelDomains: ['.ru'],
    currencyCodes: [],
  },
  {
    name: 'Rwanda',
    code: 'RW',
    alpha3Code: 'RWA',
    numericCode: '646',
    topLevelDomains: ['.rw'],
    currencyCodes: ['RWF'],
  },
  {
    name: 'Saint Barthélemy',
    code: 'BL',
    alpha3Code: 'BLM',
    numericCode: '652',
    topLevelDomains: ['.bl'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Saint Helena Ascension Island Tristan da Cunha',
    code: 'SH',
    alpha3Code: 'SHN',
    numericCode: '654',
    topLevelDomains: ['.sh'],
    currencyCodes: [],
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    alpha3Code: 'KNA',
    numericCode: '659',
    topLevelDomains: ['.kn'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    alpha3Code: 'LCA',
    numericCode: '662',
    topLevelDomains: ['.lc'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Saint Martin (French part)',
    code: 'MF',
    alpha3Code: 'MAF',
    numericCode: '663',
    topLevelDomains: ['.mf'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    alpha3Code: 'SPM',
    numericCode: '666',
    topLevelDomains: ['.pm'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    alpha3Code: 'VCT',
    numericCode: '670',
    topLevelDomains: ['.vc'],
    currencyCodes: ['XCD'],
  },
  {
    name: 'Samoa',
    code: 'WS',
    alpha3Code: 'WSM',
    numericCode: '882',
    topLevelDomains: ['.ws'],
    currencyCodes: ['USD', 'WST'],
  },
  {
    name: 'San Marino',
    code: 'SM',
    alpha3Code: 'SMR',
    numericCode: '674',
    topLevelDomains: ['.sm'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    alpha3Code: 'STP',
    numericCode: '678',
    topLevelDomains: ['.st'],
    currencyCodes: [],
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    alpha3Code: 'SAU',
    numericCode: '682',
    topLevelDomains: ['.sa'],
    currencyCodes: ['SAR'],
  },
  {
    name: 'Senegal',
    code: 'SN',
    alpha3Code: 'SEN',
    numericCode: '686',
    topLevelDomains: ['.sn'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Serbia',
    code: 'RS',
    alpha3Code: 'SRB',
    numericCode: '688',
    topLevelDomains: ['.rs'],
    currencyCodes: ['RSD'],
  },
  {
    name: 'Seychelles',
    code: 'SC',
    alpha3Code: 'SYC',
    numericCode: '690',
    topLevelDomains: ['.sc'],
    currencyCodes: ['SCR'],
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    alpha3Code: 'SLE',
    numericCode: '694',
    topLevelDomains: ['.sl'],
    currencyCodes: ['SLL'],
  },
  {
    name: 'Singapore',
    code: 'SG',
    alpha3Code: 'SGP',
    numericCode: '702',
    topLevelDomains: ['.sg'],
    currencyCodes: ['SGD'],
  },
  {
    name: 'Sint Maarten (Dutch part)',
    code: 'SX',
    alpha3Code: 'SXM',
    numericCode: '534',
    topLevelDomains: ['.sx'],
    currencyCodes: ['ANG'],
  },
  {
    name: 'Slovakia',
    code: 'SK',
    alpha3Code: 'SVK',
    numericCode: '703',
    topLevelDomains: ['.sk'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Slovenia',
    code: 'SI',
    alpha3Code: 'SVN',
    numericCode: '705',
    topLevelDomains: ['.si'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    alpha3Code: 'SLB',
    numericCode: '090',
    topLevelDomains: ['.sb'],
    currencyCodes: ['SBD'],
  },
  {
    name: 'Somalia',
    code: 'SO',
    alpha3Code: 'SOM',
    numericCode: '706',
    topLevelDomains: ['.so'],
    currencyCodes: ['SOS'],
  },
  {
    name: 'South Africa',
    code: 'ZA',
    alpha3Code: 'ZAF',
    numericCode: '710',
    topLevelDomains: ['.za'],
    currencyCodes: ['ZAR'],
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    alpha3Code: 'SGS',
    numericCode: '239',
    topLevelDomains: ['.gs'],
    currencyCodes: [],
  },
  {
    name: 'South Sudan',
    code: 'SS',
    alpha3Code: 'SSD',
    numericCode: '728',
    topLevelDomains: ['.ss'],
    currencyCodes: ['SSP'],
  },
  {
    name: 'Spain',
    code: 'ES',
    alpha3Code: 'ESP',
    numericCode: '724',
    topLevelDomains: ['.es'],
    currencyCodes: ['EUR'],
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    alpha3Code: 'LKA',
    numericCode: '144',
    topLevelDomains: ['.lk'],
    currencyCodes: ['LKR'],
  },
  {
    name: 'Sudan',
    code: 'SD',
    alpha3Code: 'SDN',
    numericCode: '729',
    topLevelDomains: ['.sd'],
    currencyCodes: ['SDG', 'SSP'],
  },
  {
    name: 'Suriname',
    code: 'SR',
    alpha3Code: 'SUR',
    numericCode: '740',
    topLevelDomains: ['.sr'],
    currencyCodes: ['SRD'],
  },
  {
    name: 'Svalbard Jan Mayen',
    code: 'SJ',
    alpha3Code: 'SJM',
    numericCode: '744',
    topLevelDomains: [''],
    currencyCodes: ['NOK'],
  },
  {
    name: 'Sweden',
    code: 'SE',
    alpha3Code: 'SWE',
    numericCode: '752',
    topLevelDomains: ['.se'],
    currencyCodes: ['SEK'],
  },
  {
    name: 'Switzerland',
    code: 'CH',
    alpha3Code: 'CHE',
    numericCode: '756',
    topLevelDomains: ['.ch'],
    currencyCodes: ['CHE', 'CHF', 'CHW'],
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    alpha3Code: 'SYR',
    numericCode: '760',
    topLevelDomains: ['.sy'],
    currencyCodes: [],
  },
  {
    name: 'Taiwan (Province of China)',
    code: 'TW',
    alpha3Code: 'TWN',
    numericCode: '158',
    topLevelDomains: ['.tw'],
    currencyCodes: [],
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    alpha3Code: 'TJK',
    numericCode: '762',
    topLevelDomains: ['.tj'],
    currencyCodes: ['TJS'],
  },
  {
    name: 'Tanzania, the United Republic of',
    code: 'TZ',
    alpha3Code: 'TZA',
    numericCode: '834',
    topLevelDomains: ['.tz'],
    currencyCodes: [],
  },
  {
    name: 'Thailand',
    code: 'TH',
    alpha3Code: 'THA',
    numericCode: '764',
    topLevelDomains: ['.th'],
    currencyCodes: ['THB'],
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    alpha3Code: 'TLS',
    numericCode: '626',
    topLevelDomains: ['.tl'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Togo',
    code: 'TG',
    alpha3Code: 'TGO',
    numericCode: '768',
    topLevelDomains: ['.tg'],
    currencyCodes: ['XOF'],
  },
  {
    name: 'Tokelau',
    code: 'TK',
    alpha3Code: 'TKL',
    numericCode: '772',
    topLevelDomains: ['.tk'],
    currencyCodes: ['NZD'],
  },
  {
    name: 'Tonga',
    code: 'TO',
    alpha3Code: 'TON',
    numericCode: '776',
    topLevelDomains: ['.to'],
    currencyCodes: ['TOP'],
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    alpha3Code: 'TTO',
    numericCode: '780',
    topLevelDomains: ['.tt'],
    currencyCodes: ['TTD'],
  },
  {
    name: 'Tunisia',
    code: 'TN',
    alpha3Code: 'TUN',
    numericCode: '788',
    topLevelDomains: ['.tn'],
    currencyCodes: ['TND'],
  },
  {
    name: 'Turkey',
    code: 'TR',
    alpha3Code: 'TUR',
    numericCode: '792',
    topLevelDomains: ['.tr'],
    currencyCodes: ['TRY'],
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    alpha3Code: 'TKM',
    numericCode: '795',
    topLevelDomains: ['.tm'],
    currencyCodes: ['TMT'],
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    alpha3Code: 'TCA',
    numericCode: '796',
    topLevelDomains: ['.tc'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    alpha3Code: 'TUV',
    numericCode: '798',
    topLevelDomains: ['.tv'],
    currencyCodes: ['AUD'],
  },
  {
    name: 'Uganda',
    code: 'UG',
    alpha3Code: 'UGA',
    numericCode: '800',
    topLevelDomains: ['.ug'],
    currencyCodes: ['UGX'],
  },
  {
    name: 'Ukraine',
    code: 'UA',
    alpha3Code: 'UKR',
    numericCode: '804',
    topLevelDomains: ['.ua'],
    currencyCodes: ['UAH'],
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    alpha3Code: 'ARE',
    numericCode: '784',
    topLevelDomains: ['.ae'],
    currencyCodes: ['AED'],
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    code: 'GB',
    alpha3Code: 'GBR',
    numericCode: '826',
    topLevelDomains: ['.gb', '.uk'],
    currencyCodes: [],
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    alpha3Code: 'UMI',
    numericCode: '581',
    topLevelDomains: [''],
    currencyCodes: ['USD'],
  },
  {
    name: 'United States of America',
    code: 'US',
    alpha3Code: 'USA',
    numericCode: '840',
    topLevelDomains: ['.us'],
    currencyCodes: [],
  },
  {
    name: 'Uruguay',
    code: 'UY',
    alpha3Code: 'URY',
    numericCode: '858',
    topLevelDomains: ['.uy'],
    currencyCodes: ['UYI', 'UYU', 'UYW'],
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    alpha3Code: 'UZB',
    numericCode: '860',
    topLevelDomains: ['.uz'],
    currencyCodes: ['UZS'],
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    alpha3Code: 'VUT',
    numericCode: '548',
    topLevelDomains: ['.vu'],
    currencyCodes: ['VUV'],
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    code: 'VE',
    alpha3Code: 'VEN',
    numericCode: '862',
    topLevelDomains: ['.ve'],
    currencyCodes: [],
  },
  {
    name: 'Viet Nam',
    code: 'VN',
    alpha3Code: 'VNM',
    numericCode: '704',
    topLevelDomains: ['.vn'],
    currencyCodes: [],
  },
  {
    name: 'Virgin Islands (British)',
    code: 'VG',
    alpha3Code: 'VGB',
    numericCode: '092',
    topLevelDomains: ['.vg'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Virgin Islands (U.S.)',
    code: 'VI',
    alpha3Code: 'VIR',
    numericCode: '850',
    topLevelDomains: ['.vi'],
    currencyCodes: ['USD'],
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    alpha3Code: 'WLF',
    numericCode: '876',
    topLevelDomains: ['.wf'],
    currencyCodes: ['XPF'],
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    alpha3Code: 'ESH',
    numericCode: '732',
    topLevelDomains: [''],
    currencyCodes: ['MAD'],
  },
  {
    name: 'Yemen',
    code: 'YE',
    alpha3Code: 'YEM',
    numericCode: '887',
    topLevelDomains: ['.ye'],
    currencyCodes: ['YER'],
  },
  {
    name: 'Zambia',
    code: 'ZM',
    alpha3Code: 'ZMB',
    numericCode: '894',
    topLevelDomains: ['.zm'],
    currencyCodes: ['ZMW'],
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    alpha3Code: 'ZWE',
    numericCode: '716',
    topLevelDomains: ['.zw'],
    currencyCodes: ['ZWL'],
  },
];
